- src/index.ts
- src/variables.ts
Signed-off-by: Andreia Ocanoaia <andreia.ocanoaia@gmail.com>
> Fix error when user is not auth

- src/commands.ts
- src/index.ts
- src/utils/file.ts
Fixes ungraceful failures for `genezio deploy` and `genezio local` when genezio.yaml is not present.
Updates another check of genezio.yaml to use the same underlying function.
> Add checks for yaml file to exist before deployment

- src/commands.ts
- src/index.ts
Signed-off-by: Andreia Ocanoaia <andreia.ocanoaia@gmail.com>
> Delete `genezio generateSdk`.

- src/index.ts
Signed-off-by: Andreia Ocanoaia <andreia.ocanoaia@gmail.com>
> Delete unused import

- src/commands.ts
Signed-off-by: Virgil993 <turcu.virgil@gmail.com>
> Fix path delimiter for Windows and Unix.

- README.md
- [default value: ]
- Move “Check our examples” at 4th step before Test your code Locally
- Add genez.io app link in documentation
- Learn more with genz.io
> updates based on Virgil's feedback

- package-lock.json
- package.json
- src/bundlers/javascript/nodeJsBinaryDepenciesBundler.ts
- src/bundlers/javascript/nodeJsBundler.ts
- src/commands.ts
- src/index.ts
- src/localEnvironment.ts
- src/requests/deployCode.ts
- src/utils/file.ts
- src/utils/lambdaHander.ts
- src/utils/logging.ts
- src/variables.ts
- tests/projectConfiguration.test.ts
Modified all console.log and console.error calls to use log.info / log.debug / log.warn and log.error accordingly.
> Change console logs to use loglevel

- src/commands.ts
- src/index.ts
- src/requests/deleteProject.ts
- src/requests/listProjects.ts
Add `genezio delete` with 2 arguments:
projectId: which project to delete; if no id is given, lists all deployed projects
-f: whether or not to skip the confirmation prompt for deletion
> Add genezio delete command in CLI

- src/index.ts
> GNZ-320 Add more explicit error messages for internal server errors

- src/index.ts
> GNZ-363 Fix --force for genezio delete

- src/index.ts
- src/localEnvironment.ts
Fix the following bugs for `genezio local`:
* gracefully exit if `genezio.yaml` is not found
* gracefully catch error if port is in used
> GNZ-365 Fix error catching for `genezio local`

- src/commands.ts
> Fix `delete project`

- package-lock.json
- package.json
- src/commands.ts
- src/index.ts
- src/requests/listProjects.ts
genezio ls - list summary for all projects
-l -> more details for each project
genezio ls <name/id> - lists only one project for provided identifier
> Gnz 239 genezio ls command

- README.md
> GNZ-370 Update README.md

- src/commands.ts
- src/index.ts
- src/utils/strings.ts
> GNZ-401 Sanitize error handling

- tests/requests/getPresignedURL.test.ts
- tests/requests/uploadContentToS3.test.ts
> Add unit tests for S3 requests.

- src/bundlers/typescript/nodeTsBundler.ts
> GNZ-443 tsconfig.json file not found causes bug

- src/models/yamlProjectConfiguration.ts
- tests/projectConfiguration.test.ts
- I also fixed unit tests
- Delete the unit tests that were duplicated
> Add checks and tests for sdk.options

- src/commands/local.ts
- src/generateSdk/astGenerator/DartAstGenerator.ts
- src/generateSdk/astGeneratorHandler.ts
- src/generateSdk/sdkGenerator/DartSdkGenerator.ts
- src/models/genezioModels.ts
We automatically generate the methods that parse the custom Dart objects. This allows the user to use any object as parameter or return type.
- [x ] New feature (non-breaking change which adds functionality)
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code
- [ x] I have made corresponding changes to the documentation
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
> Add support for parsing custom Dart objects in Dart sdk.

- src/bundlers/dart/dartBundler.ts
- src/generateSdk/sdkGenerator/DartSdkGenerator.ts
Fixing a bug where non dart files were not included in build. For example, this was problematic since the .env was not included.
Tested with a project that requires .env file.
> Fix bug where non dart files were not included in AWS Lambda.

- src/generateSdk/astGenerator/DartAstGenerator.ts
- src/generateSdk/sdkGenerator/DartSdkGenerator.ts
- src/models/genezioModels.ts
Void methods were not handled properly.
With integration tests.
> Handle void methods. Various other bug fixes.

- src/bundlers/bundler.interface.ts
- src/bundlers/dart/dartBundler.ts
- src/bundlers/dart/dartMain.ts
- src/bundlers/dart/localDartBundler.ts
- src/bundlers/dart/localDartMain.ts
- src/commands/deploy.ts
- src/commands/local.ts
- src/generateSdk/generateSdkApi.ts
- src/generateSdk/sdkGenerator/DartSdkGenerator.ts
- src/models/genezioModels.ts
- src/models/projectConfiguration.ts
- src/models/sdkGeneratorResponse.ts
- src/utils/dartAstCasting.ts
- tests/requests/deployCode.test.ts
With this PR, we support returning List and Maps and also passing as parameters List and Maps.
Tested with integration tests.
> Offer better support for types in Dart SDK.

- src/generateSdk/astGenerator/TsAstGenerator.ts
- src/generateSdk/sdkGenerator/PythonSdkGenerator.ts
- src/generateSdk/sdkGenerator/TsSdkGenerator.ts
- src/generateSdk/templates/pythonSdk.ts
- src/models/genezioModels.ts
Add an option for explicit void return type in typescript ast and solve an issue that would break the python SDK on void functions (check the existence of `result` in the remote file)
Manual testing
> void functions in python sdk

- src/bundlers/dart/dartBundler.ts
- src/bundlers/javascript/nodeJsBundler.ts
- src/bundlers/typescript/nodeTsBundler.ts
- src/commands/deploy.ts
- src/generateSdk/templates/browserSdkJs.ts
- src/generateSdk/templates/browserSdkTs.ts
- src/generateSdk/templates/nodeSdkJs.ts
- src/generateSdk/templates/nodeSdkTs.ts
- src/utils/file.ts
> added temp folder cleanup

- src/bundlers/dart/localDartBundler.ts
- src/commands/local.ts
- src/generateSdk/astGenerator/DartAstGenerator.ts
- src/generateSdk/astGeneratorHandler.ts
Bug fix for problem when an error was occurring when user was testing locally a project with more then one class
-  Bug fix (non-breaking change which fixes an issue)
Manually with a project with two classes.
> GNZ-735: Error when testing two classes locally

- src/bundlers/dart/dartMain.ts
- src/bundlers/javascript/lambdaHander.ts
> Add support to raw body in http mode

- src/errors.ts
- src/generateSdk/astGenerator/DartAstGenerator.ts
- src/generateSdk/sdkGenerator/DartSdkGenerator.ts
Throw error if user uses optional in Dart.
Manually
> GNZ-742: Throw error if user uses optional in dart

- package-lock.json
- package.json
- src/errors.ts
- src/generateSdk/astGenerator/DartAstGenerator.ts
- src/utils/dart.ts
Check if `dartaotruntime` is installed before proceeding with the Dart bundling and SDK generating processes.
Manually.
> GNZ-764: Check if dartaotruntime is installed

- src/utils/dartAstCasting.ts
Fix error where Future<void> as return type of a method was mapped to Future<Object>.
Manually.
> GNZ-734: Handle future void return dart

- src/generateSdk/astGenerator/TsAstGenerator.ts
- src/generateSdk/sdkGenerator/PythonSdkGenerator.ts
- src/generateSdk/sdkGenerator/TsSdkGenerator.ts
- src/models/genezioModels.ts
Manually and with integration tests.
> GNZ-740: Add support for both string and number types

- src/generateSdk/sdkGenerator/DartSdkGenerator.ts
Removing an unwanted `console.log`.
Manually, by running `genezio local`.
> Remove accidental log

- src/generateSdk/utils/getAstSummary.ts
> send new type structure tu ast summary

- src/models/yamlProjectConfiguration.ts
> added name of clases in yaml

- src/bundlers/dart/dartMain.ts
Fix warnings in the dart template to be compliant with dart v3.0.0.
> Fix warnings in dart main template.

- .github/workflows/unit-test.yaml
Add command in CI/CD pipeline to check if genezio builds successfully.
> Add CI/CD command to check if genezio builds

- src/commands/local.ts
- src/utils/webpack.ts
> added source map

- package-lock.json
- package.json
> Revert "Bump open from 8.4.2 to 9.1.0"

- package-lock.json
- package.json
Security dependency update for yaml to 2.2.2
> Manual update yaml to 2.2.2

- src/cloudAdapter/genezioAdapter.ts
- src/cloudAdapter/selfHostedAwsAdapter.ts
- src/utils/file.ts
> GNZ-678: Check file size

- src/generateSdk/astGenerator/DartAstGenerator.ts
Remove DateTime from unsupported list because we are supporting it from now on.
> GNZ-774 Remove DateTime from unsupported list

- .github/pull_request_template.md
Simplify the pull request template.
> Update the pull requests template.

- package-lock.json
- src/commands/local.ts
> genezio fix restart

- README.md
Update README with a commands summary.
> Add commands description in README.

- src/commands/init.ts
> Change log.info to console.log to ensure that the text is always printed

- src/bundlers/javascript/nodeJsBundler.ts
- src/bundlers/javascript/nodeJsDependenciesBundler.ts
- src/bundlers/typescript/nodeTsBundler.ts
- src/bundlers/typescript/nodeTsDependenciesBundler.ts
- src/commands/deploy.ts
- src/models/nodeRuntime.ts
- src/models/projectConfiguration.ts
- src/models/yamlProjectConfiguration.ts
- src/requests/deployCode.ts
> Bug fix: Bring all dependencies as a temporary fix.

- src/utils/file.ts
Fix a bug in `fileExists` function where the returned promise would never resolve.
> Bugfix: Fix fileExists issue

- src/commands/init.ts
- src/utils/strings.ts
- tests/commands.test.ts
This PR:
- removes the comments from `genezio init` because they are not useful anymore
- changes defaults to `ts` instead of `js`
- on error, it keeps requesting the correct answers to the questions
> GNZ-883 Update genezio init

- package-lock.json
- package.json
Removing `http-terminator` dependency because:
- it is not used in our codebase
- it has a dependency - `string-similarity` which is no longer maintained[1] and throws a deprecation warning
This PR also adds a newly generated `package-lock.json`.
[1] https://www.npmjs.com/package/string-similarity
> Remove http-terminator dependency

- src/commands/local.ts
Moved the closing of the watcher at the end of the loop that looks for changes. This way, it is cleaned at the same time with the other resources.
> Fix a bug when the watcher closed too early

- tests/commands.test.ts
We no longer test `genezio init` using integration tests.
Hence, this PR adds throughout unit tests for `genezio init`.\
> Add unit tests for genezio init

- src/bundlers/dart/dartMain.ts
- src/bundlers/javascript/lambdaHandler.ts
> Add the header `x-powered-by: genezio` to uniquely identify genezio

- src/bundlers/node/lambdaHander.ts
> Fix genezio header

- src/commands/local.ts
During `genezio local`, jsonrpc handlers were not expecting the response output to be the same format as http handlers.
> Fix for "genezio local"

- src/bundlers/node/nodeJsBundler.ts
> Fix Windows path

- src/bundlers/dart/localDartMain.ts
The local server expects a JSON object as a response with a body field.
> Encode dart local response

- src/models/cloudProviderIdentifier.ts
- src/models/yamlProjectConfiguration.ts
This PR:
- Fixes a mini bug - changes the default value from "aws" to "genezio".
- Checks if a supported cloud provider is set in `genezio.yaml`.
> Add checks for the cloud provider setting

- src/commands/deploy.ts
- src/utils/checkClassesMethods.ts
- src/utils/getNoMethodClasses.ts
If we use genezio deploy and we don't have methods in our classes, we display a better error.
> fix: error for classes without methods

- package-lock.json
- package.json
- src/bundlers/node/lambdaHandler.ts
- src/commands/local.ts
- src/genezio.ts
- src/models/commandOptions.ts
> Load variables from `.env` file if it exists in `genezio local`

- src/bundlers/dart/dartBundler.ts
- src/bundlers/node/nodeJsBundler.ts
remove .git file from nonJsFiles and nonDartFiles
> filter .git file from nonJsFiles and nonDartFiles

- src/bundlers/node/lambdaHandler.ts
> remove logic for removing env vars in handler

- src/bundlers/dart/dartBundler.ts
- src/utils/process.ts
We were swallowing errors that occured during hooks. Now we show all errors.
> Show stderr when an error occurs during pre hook scripts.

- src/bundlers/dart/dartBundler.ts
- src/bundlers/node/nodeJsBundler.ts
- src/utils/file.ts
Files were not properly copied during bundling process on windows.
> Fix for the problem where files were not properly copied during bundling on windows.

- src/commands/deploy.ts
Signed-off-by: Andreia Ocanoaia <>
This PR sanitizes the subdomain set in `genezio.yaml`. A domain should only contain letters, numbers and hyphens.
> Sanitize genezio domain.

- src/bundlers/dart/dartBundler.ts
- src/bundlers/node/nodeJsBinaryDependenciesBundler.ts
- src/cloudAdapter/aws/cloudFormationBuilder.ts
- src/cloudAdapter/aws/selfHostedAwsAdapter.ts
- src/cloudAdapter/genezio/genezioAdapter.ts
- src/generateSdk/astGenerator/JsAstGenerator.ts
- src/generateSdk/astGeneratorHandler.ts
- src/generateSdk/sdkGenerator/DartSdkGenerator.ts
- src/generateSdk/sdkGenerator/JsSdkGenerator.ts
- src/generateSdk/sdkGenerator/PythonSdkGenerator.ts
- src/generateSdk/sdkGenerator/SwiftSdkGenerator.ts
- src/generateSdk/sdkGenerator/TsSdkGenerator.ts
- src/generateSdk/templates/nodeSdkJs.ts
- src/generateSdk/templates/nodeSdkTs.ts
- src/generateSdk/templates/pythonSdk.ts
- src/generateSdk/templates/swiftSdk.ts
- src/models/yamlProjectConfiguration.ts
- src/requests/axios.ts
- src/telemetry/sdk/analyticsHandler.sdk.ts
- src/telemetry/sdk/remote.ts
- src/telemetry/session.ts
- src/utils/accounts.ts
- src/utils/version.ts
Fix all the typos across the codebase with Code SpellChecker.
> Fix typos across the codebase

- src/commands/login.ts
Added some next steps for the user after `genezio login`
> Feature/gnz 1105 how to after login 

- .gitignore
- package.json
- src/commands/init.ts
- src/genezio.ts
- tests/commands.test.ts
add genezio init <path>
Example: if path = . add genezio.yaml in the same folder
> Add possibility to give the folder name in genezio init

- src/bundlers/kotlin/kotlinBundler.ts
- src/bundlers/kotlin/kotlinMain.ts
- src/bundlers/kotlin/localKotlinBundler.ts
- src/bundlers/kotlin/localKotlinMain.ts
- src/commands/deploy.ts
- src/commands/local.ts
- src/generateSdk/astGenerator/KotlinAstGenerator.ts
- src/generateSdk/astGeneratorHandler.ts
- src/generateSdk/sdkGenerator/KotlinSdkGenerator.ts
- src/generateSdk/sdkGeneratorHandler.ts
- src/generateSdk/templates/kotlinSdk.ts
- src/models/yamlProjectConfiguration.ts
- src/utils/kotlin.ts
- src/utils/kotlinAstCasting.ts
- src/utils/languages.ts
- tests/commands.test.ts
- New language support for backend deployments: Kotlin
- Can be deployed locally, on AWS Lambda or Function Runtime
- Small change to archive creation logic: ZIP step is skipped for Kotlin deployments to AWS Lambda due to it being unable to parse jar files
- Requires PR#140 in genezio-backend to be merged first
> Add kotlin local, aws & capybara deploy support

- src/commands/init.ts
- tests/commands.test.ts
Add a complete yaml with all the configs, but commented out
> GNZ-1123 Genezio init add a complete yaml with all the configs

- src/commands/deploy.ts
- src/commands/generateSdk.ts
- src/requests/getEnvironmentVariables.ts
- src/requests/getProjectInfo.ts
- src/requests/setEnvironmentVariables.ts
We changed the endpoints in the backend and we also have to change them in the CLI.
> Switch endpoints to their new versions.

- src/commands/deploy.ts
- src/utils/accounts.ts
> append genezio registry credentials instead of writing to file

- src/bundlers/node/nodeJsBundler.ts
After the latest changes, if you use a worspace and you don't have a package.json in your server/ folder, the CLI will crash. We fixed this to offer 100% backwards compatilbity.
> Backwards compatibility fix

- src/bundlers/node/dependencyInstaller.ts
- src/bundlers/node/nodeJsBundler.ts
- src/bundlers/node/typescriptRequiredDepsBundler.ts
The dependencies were not properly installed because of a bug introduced during the workspace work. Also the package.json was not properly copied to the temp folder.
> Fix issue with binary deps caused by the workspace feature

- src/bundlers/node/nodeJsBundler.ts
- src/utils/configuration.ts
- src/utils/file.ts
> Wrong absolute path when relative should be used

- src/commands/addClass.ts
- src/commands/login.ts
- src/generateSdk/templates/newProject.ts
- tests/commands.test.ts
> changed addClass cmd and fix text at genezio login

- src/models/yamlProjectConfiguration.ts
Fix issue when genezio local was writing absolute paths in workspace yaml file
> Fix issue when genezio local was writing absolute paths in workspace yaml file

- src/commands/addClass.ts
- src/commands/superGenezio.ts
- src/genezio.ts
- src/index.ts
- src/utils/configs.ts
- tsconfig.json
> fix genezio super cmd

- src/commands/deploy.ts
- src/commands/local.ts
- src/utils/reporter.ts
SDK was not properly generated for old genezio projects.
> Mantain backwards compatibility SDK

- .npmrc
- package.json
Increase node minim version to node 16.
> Increase node minim requirement

- src/commands/deploy.ts
- src/models/cloudProviderIdentifier.ts
Improvement
Add capybaraLinux cloud provider option to the list of known providers.
> Add capybaraLinux cloud provider option

- .github/workflows/release.yaml
Automate genezio CLI releases using a Github Action.
> Add github action for release.

- src/bundlers/node/nodeJsBundler.ts
Add line and column numbers to require error. Also, skip check if the file is in node_modules, even though the node_modules folder is not inside the project.
> add line and column for relative require error and check for dev-deps in other node_modules

- src/commands/deploy.ts
- src/commands/local.ts
Fix the current path for .env files when `genezio deploy --env <path>` is used.
The `<path>` should be relative to the current directory, not to the backend workspace directory.
> Fix path for .env files when using --env

- package-lock.json
- package.json
By lowering the version of the lint-staged, we can support Node 16 until further notice.
> Use lint-staged 14.0.1 to enable the usage of Node 16

- .github/workflows/unit-test.yaml
We want to test that our CLI passes the unit tests on all the supported platforms and node versions.
> Improve unit tests by adding multiple node versions and platforms

- src/commands/deploy.ts
- src/generateSdk/astGenerator/KotlinAstGenerator.ts
- src/utils/process.ts
Removes spam logs that come from running pre deploy scripts.
Closes #486
---
> ## TL;DR
> This pull request makes changes to the `deploy.ts`, `KotlinAstGenerator.ts`, and `process.ts` files. It modifies the logging statements and adds a check for the success of the `runNewProcess` function. It also updates the `runNewProcess` function to default the `showStdoutOutput` parameter to `false`.
> 
> ## What changed
> - In the `process.ts` file, the `runNewProcess` function was updated to default the `showStdoutOutput` parameter to `false`.
> - In the `deploy.ts` and `KotlinAstGenerator.ts` files the variables that store if the command ran …
> Remove noisy logs from `genezio deploy`

- src/bundlers/node/lambdaHandler.ts
Adds a new error that can be read by the user in the Test Interface when the constructor call fails.
> Handle constructor call failures and report them

- .github/workflows/dependabot.yaml
Enable dependabot auto-merging for PRs opened by dependabot that don't require an approval.
> Enable dependabot auto-merging for PRs that don't require an approval

- .github/workflows/dependabot.yaml
> Dependabot should perform squash commits

- src/bundlers/bundler.interface.ts
- src/bundlers/dart/dartBundler.ts
- src/generateSdk/sdkGenerator/KotlinSdkGenerator.ts
- src/generateSdk/sdkGenerator/PythonSdkGenerator.ts
- src/generateSdk/sdkGeneratorHandler.ts
- src/generateSdk/utils/getAstSummary.ts
- src/index.ts
- src/requests/getCompileDartPresignedURL.ts
- src/telemetry/session.ts
- src/telemetry/telemetry.ts
- src/utils/file.ts
- src/utils/process.ts
- tests/commands.test.ts
Fixes some of the errors reported by ESLint.
> Fix some ESLint errors

- src/bundlers/dart/dartBundler.ts
- src/commands/addClass.ts
- src/commands/deploy.ts
- src/generateSdk/astGenerator/JsAstGenerator.ts
- src/generateSdk/astGeneratorHandler.ts
- src/generateSdk/sdkGenerator/DartSdkGenerator.ts
- src/generateSdk/sdkGenerator/KotlinSdkGenerator.ts
- src/generateSdk/sdkGenerator/PythonSdkGenerator.ts
- src/generateSdk/sdkGenerator/SwiftSdkGenerator.ts
- src/utils/genezioRequestParser.ts
- src/utils/stripDecoratorsPlugin.ts
- tests/commands.test.ts
> Fix some more ESLint errors

- src/commands/local.ts
- src/generateSdk/utils/compileSdk.ts
- src/models/yamlProjectConfiguration.ts
- src/packageManagers/npm.ts
- src/packageManagers/packageManager.ts
- src/packageManagers/pnpm.ts
- src/packageManagers/yarn.ts
Adds a package manager wrapper that can be used anywhere in the application.
Adds implementation for 3 package managers: npm, yarn, pnpm.
> Add a package manager wrapper for the CLI

- src/bundlers/node/dependencyInstaller.ts
- src/bundlers/node/nodeJsBinaryDependenciesBundler.ts
- src/commands/local.ts
- src/generateSdk/astGeneratorHandler.ts
- src/generateSdk/utils/compileSdk.ts
- src/genezio.ts
- src/utils/file.ts
- src/utils/reporter.ts
Replaces all the old usages of the `npm install` with the new package manager wrapper.
> Use the new Package Manager wrapper in the CLI

- src/commands/deploy.ts
- src/commands/logout.ts
- src/genezio.ts
- src/utils/accounts.ts
Instead of writing directly in the package manager configuration
file, use the API provided by the package manager interface.
> Use the package manager interface for login and logout

- src/utils/calculateBiggestProjectFiles.ts
- src/utils/configuration.ts
- src/utils/file.ts
- src/utils/linkDatabase.ts
Fix some more ESLint warnings that gets the CLI closer to the goal of having NO ESLint warnings.
> Fix eslint warnings

- src/commands/addClass.ts
- src/commands/deploy.ts
- src/commands/generateSdk.ts
- src/commands/list.ts
- src/commands/local.ts
- src/commands/login.ts
- src/genezio.ts
- src/index.ts
- src/requests/deleteProject.ts
> Add await for GenezioTelemetry.sendEvent to send events reliably

- src/bundlers/dart/dartBundler.ts
- src/cloudAdapter/genezio/genezioAdapter.ts
- src/requests/createFrontendProject.ts
- src/requests/deleteProject.ts
- src/requests/deployCode.ts
- src/requests/getCompileDartPresignedURL.ts
- src/requests/getEnvironmentVariables.ts
- src/requests/getFrontendPresignedURL.ts
- src/requests/getPresignedURL.ts
- src/requests/getProjectInfo.ts
- src/requests/listProjects.ts
- src/requests/models.ts
- src/requests/setEnvironmentVariables.ts
- src/requests/uploadContentToS3.ts
- src/utils/sdk.ts
- tests/requests/deployCode.test.ts
- tests/requests/getPresignedURL.test.ts
> Add typing for Axios backend requests

- .github/ISSUE_TEMPLATE/task.yml
- .github/dependabot.yaml
- .github/pull_request_template.md
- .github/workflows/release.yaml
- .github/workflows/unit-test.yaml
- .gitmodules
- README.md
> Update `master` to `main`

- src/generateSdk/astGenerator/JsAstGenerator.ts
- src/generateSdk/astGenerator/TsAstGenerator.ts
- src/generateSdk/astGeneratorHandler.ts
- src/generateSdk/sdkGenerator/TsSdkGenerator.ts
- src/generateSdk/sdkGeneratorHandler.ts
- src/generateSdk/utils/compileSdk.ts
- src/generateSdk/utils/mapDbAstToFullAst.ts
- src/index.ts
- src/models/genezioModels.ts
Changed the TS and JS SDK/AST generation to use proper types and also throw errors for unsupported language features.
> Fix ESLint errors related to SDK and AST generation for TS and JS

- package-lock.json
- package.json
This PR changes `^` to `~` to restrict major and minor patches for sentry dependencies.
This is done to avoid breaking the genezio cli in production due to dependency releases.
> [HOT FIX] Restrict @sentry dependencies to only patch updates

- src/utils/localDockerDatabase.ts
> added an adaptive log in localDockerDatabase.ts

- package-lock.json
- src/commands/delete.ts
- src/commands/deploy.ts
- src/commands/list.ts
- src/commands/local.ts
- src/commands/login.ts
- src/generateSdk/generateSdkApi.ts
- src/models/cloudProviderIdentifier.ts
- src/utils/genezioRequestParser.ts
> Fix ESLint errors related to commands

- src/generateSdk/astGenerator/TsAstGenerator.ts
- src/generateSdk/sdkGenerator/TsSdkGenerator.ts
We now support:
```ts
type A = {
s: "myCustomString";
b: true;
n: 23;
}
```
> Add TS AST litreal retention

- src/commands/deploy.ts
- src/generateSdk/templates/packageJson.ts
- src/generateSdk/utils/compileSdk.ts
- src/models/yamlProjectConfiguration.ts
- src/packageManagers/npm.ts
- src/packageManagers/packageManager.ts
- src/packageManagers/pnpm.ts
- src/packageManagers/yarn.ts
- src/utils/reporter.ts
I also added the documentation in dev
> Add support for public sdk using npm / yarn / pnpm

- package-lock.json
- package.json
- tests/commands/superGenezio/createNewProject.test.ts
- tests/commands/superGenezio/superGenezio.test.ts
- vitest.config.ts
> Add genezio supercommand tests

- package.json
- src/cloudAdapter/aws/cloudFormationBuilder.ts
- src/cloudAdapter/aws/selfHostedAwsAdapter.ts
- src/commands/local.ts
- src/generateSdk/utils/getFiles.ts
The only ESLint problems left are now int the SDK/AST generation part of
the code which is mature already. If someone in the future will modify
this part of code, they should also fix the remaining errors.
> Reenable ESLint precommit checks and fix some issues

- src/commands/superGenezio/superGenezio.ts
genezio v0.7.1. Run with `--help` to display CLI options.
> Add a version and help banner to `genezio` super command

- package.json
> Add pre-commit checks for `console.log` and changing constants

- src/generateSdk/astGeneratorHandler.ts
- src/generateSdk/sdkGeneratorHandler.ts
> Use zod for checking custom plugins schema

- src/commands/account.ts
- src/commands/link.ts
- src/commands/login.ts
- src/commands/logout.ts
- src/genezio.ts
- src/requests/getUser.ts
- src/requests/models.ts
> Add user details on `genezio account` command

- src/commands/superGenezio/createNewProject.ts
> Hotfix: Add `cd` before running backendScripts in monorepo environment

- src/bundlers/node/genezioRuntimeHandlerGenerator.ts
- src/bundlers/node/lambdaHandlerGenerator.ts
- src/bundlers/node/nodeJsBundler.ts
- src/commands/local.ts
When using the `capybara` cloud provider, generate the node handler differently as required by the genezio runtime.
> GNZ-1336: Add handler generator for Genezio Runtime

- src/requests/axios.ts
- src/requests/createFrontendProject.ts
- src/requests/deleteProject.ts
- src/requests/deployCode.ts
- src/requests/getCompileDartPresignedURL.ts
- src/requests/getEnvironmentVariables.ts
- src/requests/getFrontendPresignedURL.ts
- src/requests/getPresignedURL.ts
- src/requests/getProjectInfo.ts
- src/requests/getTemplateList.ts
- src/requests/listProjects.ts
- src/requests/setEnvironmentVariables.ts
- tests/requests/deployCode.test.ts
- tests/requests/getPresignedURL.test.ts
Update axios error checking accordingly to #688
> Update axios error checking accordingly to #688

- src/commands/account.ts
- src/commands/deploy.ts
- src/commands/list.ts
- src/commands/superGenezio/superGenezio.ts
- src/requests/getUser.ts
- src/utils/accounts.ts
- tests/commands/superGenezio/superGenezio.test.ts
This makes the user flow easier because we login automatically for him if his token is missing or incorrect.
> Make genezio deploy, account and list automatically login if token is incorrect

- package-lock.json
- src/commands/create.ts
- src/genezio.ts
- src/models/commandOptions.ts
Adds a new `genezio create` commands that lets the user create new genezio projects starting from a template.
> Add `genezio create` command

- src/commands/create/interactive.ts
- src/commands/create/list.ts
- src/genezio.ts
> Add `genezio create templates` command that lists available templates

- scripts/checkUnwantedLogs.js
https://stackoverflow.com/a/18810673
> Make `checkUnwantedLogs` look only for modified lines

- src/utils/reporter.ts
> Add informative log about frontend start in `genezio local`

- src/models/yamlProjectConfiguration.ts
> Bug fix: Local scripts are not written back to the YAML config

- src/commands/create/list.ts
> Fix fullstack/standalone filter for `genezio create templates`

- tests/commands/create/list.test.ts
> Add test for `genezio create templates` listing

- src/commands/create/interactive.ts
- tests/commands/create/interactive.test.ts
> Add HTML color and sort templates by importance

- src/commands/create/interactive.ts
> Enable interactive Frontend template creation

- README.md
> Update README.md to reflect recent documentation changes (#723)

- src/commands/create/create.ts
> Install dependency packages after creating a new project from template

- src/bundlers/utils.ts
- src/commands/bundle.ts
- src/commands/deploy.ts
- src/genezio.ts
- src/models/commandOptions.ts
In this PR, I've implement a hidden command (it does not appear in `genezio help`) that can be used to bundle and generate the AST for a class. This is useful if you want to deploy separately a class (e.g.: auth scenario) as part of an CI/CD.
It generates in an output folder the zip that contains the bundle and the AST of that class.
> Add a hidden command that bundles a class and generates a zip and and ast summary for it.

- src/commands/create/templates.ts
> Add onboarding backend template

- package-lock.json
- package.json
- src/commands/local.ts
- src/requests/getAuthStatus.ts
- src/requests/getProjectInfoByName.ts
- src/requests/models.ts
- src/utils/servicesEnvVariables.ts
When `genezio local` is executed, we try to get the auth function url and add it to the env variables.
> Get the Auth Function URL when genezio local is executed.

- src/utils/sdk.ts
This PR fixes the integration tests fail by only deleting the sdk folder from the disk if the sdk language is typescript or javascript
> Delete sdk folder from disk only if the sdk language is js or ts

- package-lock.json
- package.json
- src/packageManagers/npm.ts
- src/packageManagers/pnpm.ts
- src/packageManagers/yarn.ts
> Use `execa` to spawn package manager commands

- src/generateSdk/sdkGenerator/JsSdkGenerator.ts
- src/generateSdk/sdkGenerator/TsSdkGenerator.ts
If on the server side, the first argument is of type `GnzContext`, the SDK will try to populate it with the token from the local storage.
> GNZ-1395 Include token in the GnzContext object if it is the first parameter

- src/commands/create/templates.ts
Adds another option for generating a backend project -> Golang
Uses the following [repository](https://github.com/Genez-io/go-backend-starter) 
> Add golang template for new project

- src/commands/create/create.ts
> Fix genezio create not copying classes from backend yaml

- src/generateSdk/sdkGenerator/JsSdkGenerator.ts
- src/generateSdk/sdkGenerator/TsSdkGenerator.ts
- src/generateSdk/templates/nodeSdkJs.ts
- src/generateSdk/templates/nodeSdkTs.ts
Move `StorageManager` in its own file instead of having one per class.
> Move storage manager in its own file.

- src/generateSdk/astGenerator/GoAstGenerator.ts
- src/generateSdk/astGenerator/JsAstGenerator.ts
- src/generateSdk/astGenerator/TsAstGenerator.ts
- src/generateSdk/sdkGenerator/GoSdkGenerator.ts
- src/generateSdk/sdkGenerator/JsSdkGenerator.ts
- src/generateSdk/sdkGenerator/TsSdkGenerator.ts
- src/generateSdk/utils/getAstSummary.ts
- src/generateSdk/utils/mapDbAstToFullAst.ts
- src/models/astSummary.ts
- src/models/genezioModels.ts
- src/models/projectConfiguration.ts
This feature allows user to document their classes and functions using language specific comment formats such as jsdoc or godoc. Those comments are now saved in the AST and added in the SDK, providing info about the function using the LSP hover functionality present in most modern IDEs.
> Docstring ast

- src/commands/create/templates.ts
Add svelte frontend template in genezio create.
> Add svelte frontend template in genezio create.

- src/utils/reporter.ts
Removing a confusing message on `genezio local` because it will become obsolete soon.
> Remove confusing message on genezio local

- src/bundlers/node/genezioRuntimeHandlerGenerator.ts
Runtime call url changed from `/CallFunction?funcId=x&method=y` to `/funcId/className/methodName`. Update the packages handler accordingly.
> Update genezio runtime handler path handling for HTTP calls

- src/commands/create/create.ts
We now add .git in the .genezioignore of templates 
> added .git to .genezioignore in all templates

- src/commands/generateSdk.ts
- src/commands/list.ts
- src/requests/listProjects.ts
- src/requests/models.ts
> Show cloud provider for genezio list.

- src/bundlers/node/typeCheckerBundler.ts
> [Type Checker Bundler] Better handle typeRoots workaround

- src/bundlers/node/lambdaHandlerGenerator.ts
- src/bundlers/node/nodeJsBundler.ts
-   [X] 🐛 Bug Fix
Lambda timeout is not handled and we lose users on that side because it looks like an internal error
> Lambda Handler Typescript Timeout error handle

- src/yamlProjectConfiguration/migration.ts
> [yaml-v2] Remove language prefix in migration script, if any

- src/bundlers/node/nodeJsBundler.ts
> [NodeJS Bundler] Attach package.json file only if present

- src/bundlers/node/lambdaHandlerGenerator.ts
- src/bundlers/node/nodeJsBundler.ts
> revert changes

- src/bundlers/go/goBundler.ts
- src/bundlers/go/goMain.ts
- src/bundlers/go/localGoBundler.ts
- src/bundlers/go/localGoMain.ts
- src/commands/local.ts
Webhook support for go. Types for HTTP requests provided at [genezio_types](https://github.com/Genez-io/genezio_types)
Also, fixes a bug that made crons unavailable from the genzio test interface
> go webhooks support

- package-lock.json
- package.json
- src/commands/create/create.ts
- src/yamlProjectConfiguration/v2.ts
- tests/commands/create/create.test.ts
> Update `genezio create` to use genezio.yaml v2

- src/commands/deploy.ts
We want to allow users to declare "frontends" that are not supposed to be deployed. Eg. CLI.
> Deploy frontend only if the `publish` field of a frontend is present

- src/commands/deploy.ts
> Run frontend `build` script before deployment

- src/yamlProjectConfiguration/migration.ts
> [yaml-v2] Fix migration when publish path is missing

- sdk-external-modules/remote-ts/package-lock.json
- src/commands/generateSdk.ts
- src/generateSdk/sdkSuccessReport.ts
- src/utils/reporter.ts
> Fix bugs that occur during genezio sdk command.

- src/yamlProjectConfiguration/migration.ts
> [yaml-v2] Fix frontend language migration

- src/bundlers/node/nodeJsBundler.ts
> Fix `--install-deps` when server path is not `.`

- src/generateSdk/sdkSuccessReport.ts
When I deploy a project without JSON-RPC classes, I want to see this info messages:
```
iulian-bogdanvlad@Iulian-Bogdans-MacBook-Pro server % genezio local --logLevel disable
✔ Running backend local scripts
Server listening on port 8083
Your local server is running and the SDK was successfully generated!
HTTP Methods Deployed:
- HelloWorldHttpExample.handleSimpleTextRequest: http://127.0.0.1:8083/HelloWorldHttpExample/handleSimpleTextRequest
- HelloWorldHttpExample.handleJsonBody: http://127.0.0.1:8083/HelloWorldHttpExample/handleJsonBody
- HelloWorldHttpExample.handleQueryParams: http://127.0.0.1:8083/HelloWorldHttpExample/handleQueryParams
- …
```
> If no SDK is generated, don't show the JS/TS import info messages.

- src/bundlers/kotlin/kotlinBundler.ts
- src/bundlers/kotlin/localKotlinBundler.ts
- src/bundlers/utils.ts
- src/commands/local.ts
- src/yamlProjectConfiguration/models.ts
> WIP kotlin fixes

- src/commands/create/create.ts
> Remove checkout to `dev` for templates

- src/utils/logging.ts
> Start spinner on adaptive log

- src/commands/create/create.ts
> Remove unnecessary `npm install` advice

- src/commands/local.ts
I fixed `nodeRuntime` to `runtime`.
> Fix warning message to correctly mention the yaml keys

- src/commands/create/templates.ts
I am adding a new flutter frontend template in the `genezio create` flow.
This PR shouldn't be push to production until this repository [1] is correctly populated.
[1] https://github.com/Genez-io/flutter-frontend-starter 
> Add flutter template in genezio create flow

- src/commands/create/templates.ts
> Add React Native template

- src/cloudAdapter/genezio/genezioAdapter.ts
- src/utils/logging.ts
> [bugfix] Change the spinners to write to stdout instead of stderr

- src/commands/create/create.ts
- src/commands/deploy.ts
- src/commands/generateSdk.ts
- src/yamlProjectConfiguration/v2.ts
Users can use `${{ variableName }}` inside scripts, these variables will be replaced by the correct value.
Supported variables:
- projectName
- stage
> Add variables to Genezio YAML scripts

- src/commands/bundle.ts
- src/genezio.ts
- src/models/cloudProviderIdentifier.ts
- src/models/commandOptions.ts
Add support for `genezio bundleClass --cloudAdapter`. This will help to build the bundle for multiple cloud adapters.
> Add support for `genezio bundleClass --cloudAdapter`

- package-lock.json
- package.json
This PR updates the test interface version to 1.0.1 to fix the issue when we have a json object in the test interface for javascript and it was turned into a string by default. Now we try to see if we can parse it as json and if we have an error at parse we just turn it into a string.
> instaled new version of test-interface

- src/generateSdk/sdkGenerator/DartSdkGenerator.ts
- src/generateSdk/sdkGenerator/JsSdkGenerator.ts
- src/generateSdk/sdkGenerator/TsSdkGenerator.ts
Add support for documentation comments to be exported in Dart SDKs.
> Add support for doc comments in Dart SDK.

- src/utils/process.ts
> Fix a bug where a command would appear as failed, even when it succeeded

- src/commands/deploy.ts
> [bugfix] Use options.subdomain if present

- src/commands/create/create.ts
- src/commands/local.ts
- src/utils/scripts.ts
> [feature] Start frontends on `genezio local`

- src/utils/scripts.ts
> Color code each frontend, if there are multiple frontends

- src/bundlers/go/goBundlerBase.ts
- src/bundlers/go/localGoBundler.ts
- src/bundlers/go/localGoMain.ts
- src/generateSdk/astGenerator/GoAstGenerator.ts
Attempt to fix the go feature for Windows...
> upgrade go ast generator to v0.1.1

- package-lock.json
- package.json
- src/constants.ts
- src/requests/gaTrackEvent.ts
- src/telemetry/telemetry.ts
> Add analytics

- src/bundlers/node/containerManifest.ts
- src/bundlers/node/nodeJsBundler.ts
- src/cloudAdapter/aws/selfHostedAwsAdapter.ts
- src/commands/local.ts
- src/models/projectConfiguration.ts
- src/models/projectOptions.ts
- src/yamlProjectConfiguration/v1.ts
- src/yamlProjectConfiguration/v2.ts
I am adding `backend.language.architecture` to allow the user to choose the architecture.
Supported values are `arm64` and `x86_64`.
Default value is `arm64`.
TODO: Update documentation.
> Expose architecture in the project options

- src/bundlers/node/clusterHandler.ts
- src/bundlers/node/nodeJsLocalBundler.ts
- src/cloudAdapter/cluster/clusterAdapter.ts
Fixes http method calls on genezio cluster deployments
> fix cluster deployments http methods

- src/commands/local.ts
Fix relative paths for local testing - when executing `genezio local`, the `cwd` should be `./server`, not `./`.
> GNZ-1589 Fix relative paths for local testing

- src/commands/local.ts
> Disable console.clear for genezio local

- src/utils/scripts.ts
> Make genezio local print stderr for frontend

- src/bundlers/node/nodeJsBundler.ts
> Add a warning when deploying to a cluster that does not exist

- src/commands/local.ts
- src/utils/scripts.ts
> Add log coloring to genezio local

- src/commands/local.ts
> [local] Throw error and stop process when backend watcher fails to start

- package-lock.json
- package.json
- src/generateSdk/sdkWriter/jsSdkWriter.ts
- src/packageManagers/npm.ts
- src/packageManagers/packageManager.ts
- src/packageManagers/pnpm.ts
- src/packageManagers/yarn.ts
The `libnpmpack` dependency was to heavy and it was causing installation problems. We a
> Remove libnpmpack and run npm pack instead

- src/telemetry/telemetry.ts
Ignore all errors that happen because of analytics.
> Catch all errors on analytics and ignore them

- src/commands/delete.ts
- src/genezio.ts
- src/models/commandOptions.ts
- src/requests/deleteProject.ts
- src/requests/deleteStage.ts
> Add a way to delete only a stage of a project

- src/genezio.ts
We always set `npm` as default package manager.
> Remove finally in try which was causing problems with package manager

- src/requests/axios.ts
> Send sentry event if axios request fails

- src/requests/deployCode.ts
> stop prepending a dot to class language

- src/bundlers/node/dependencyInstaller.ts
- src/generateSdk/sdkSuccessReport.ts
- src/generateSdk/utils/compileSdk.ts
- src/packageManagers/packageManager.ts
- src/utils/file.ts
> Fix bug with package manager selection

- src/commands/deploy.ts
- src/commands/login.ts
> Add auto-login for genezio deploy

- src/utils/scripts.ts
Execa is a more mature library than the standard library that offers
a richer API which is also crossplatform.
> Replace child_process exec with execa when running scripts

- src/bundlers/node/genezioRuntimeHandlerGenerator.ts
> Move constructor within call

- src/yamlProjectConfiguration/v2.ts
> Fix small YAML cache bug

- src/commands/bundle.ts
- src/commands/deploy.ts
- src/commands/generateSdk.ts
- src/commands/local.ts
- src/generateSdk/generateSdkApi.ts
- src/generateSdk/sdkMonitor.ts
- src/models/genezioModels.ts
- src/models/projectConfiguration.ts
- src/models/sdkGeneratorResponse.ts
Implement the change for genezio local.
Subsequent PRs implement it for delpoy, bundle and generateSdk.
> Allow multiple SDKs to be generated out of one AST

- src/commands/bundle.ts
> [bundle] Add multiple sdk generation

- src/commands/bundle.ts
- src/commands/generateSdk.ts
> [generate sdk] Add support for new multiple sdk generation

- src/commands/local.ts
> [bugfix] Fix weird line-split class process output

- src/commands/deploy.ts
- src/commands/local.ts
> [bugfix] Treat the case when the YAML `frontend` field is `undefined`

- package-lock.json
- package.json
Bump test-interface-version to v1.1.0
> bump to v1.1.0

- package-lock.json
- package.json
- src/commands/local.ts
This PR allows us to run genezio local in GitPods and Github Codespaces by checking if we have certain environment variables 
and setting the localUrl in the SDK properly
> Gitpod bugfix local

- src/commands/local.ts
Change route for codespaces to server test interface at `/` 
> handle special route for github codespaces

- src/bundlers/bundler.interface.ts
- src/bundlers/node/nodeJsLocalBundler.ts
- src/commands/deploy.ts
- src/commands/local.ts
> added faas for genezio local

- src/bundlers/node/genezioRuntimeHandlerGenerator.ts
It seems that the header comes as `Genezio-Cronstring`.
> Fix request header for cron events

- src/commands/create/interactive.ts
- src/utils/configs.ts
- src/yamlProjectConfiguration/v1.ts
- src/yamlProjectConfiguration/v2.ts
> Change supported regions

- src/bundlers/node/genezioRuntimeHandlerGenerator.ts
Handle Genezio runtime event properly
> fix rate limiter

- src/commands/deploy.ts
- src/models/projectConfiguration.ts
- src/yamlProjectConfiguration/models.ts
- src/yamlProjectConfiguration/v2.ts
> changes function type in yaml

- package-lock.json
- package.json
- src/bundlers/node/genezioRuntimeHandlerGenerator.ts
- src/bundlers/node/lambdaHandlerGenerator.ts
- src/requests/getAuthStatus.ts
- src/utils/servicesEnvVariables.ts
HOT FIX
The cloud-provider check for running a local project with authentication was wrongfully considering `GENEZIO_CLOUD` projects to be `GENEZIO_UNIKERNEL`, making the CLI think the integration is not available.
Also fixed a small inconsistency between the runtime handler and the AWS one regarding error handling.
> FIX local auth

- package-lock.json
- package.json
- src/utils/decorators/jsTsDecorators.ts
> use preset-react to support jsx syntax

- src/yamlProjectConfiguration/v2.ts
> Wrap YAMLParseError with UserError

- package-lock.json
- src/commands/deploy.ts
> Fix frontend deploy link listing

- src/utils/accounts.ts
We want to be able to run single genezio commands without globally login in.
This PR checks if GENEZIO_TOKEN is set before trying to globally authenticate.
This way we can run:
```
GENEZIO_TOKEN=<token> genezio deploy
```
This feature is useful to deploy multiple projects for different users on the same machine.
> Export GENEZIO_TOKEN to run a single command authenticated

- src/commands/deploy/command.ts
- src/commands/deploy/genezio.ts
- src/genezio.ts
This higher function will be used as a router do guide us which type of deploy
we are going to make. The classic one is a normal Genezio Deploy using classes/
functions. Upcoming deploy type is NextJS.
> Create a new `deployCommand` function that wraps the old one

- src/commands/deploy/command.ts
> Add NextJS deploy type without implementation

- src/commands/deploy/command.ts
- src/commands/deploy/nextjs.ts
Tries to read from `genezio.yaml` file the name and region of the project. If no configuration is present, the name is taken from `package.json` if valid (if not valid, is asked) and the region is asked.
> Read genezio config or ask questions about it on NextJS deploy

- src/commands/deploy/nextjs.ts
> Build NextJs project using Open-Next

- src/commands/deploy/genezio.ts
- src/commands/deploy/nextjs.ts
> Deploy NextJS functions to Genezio

- package.json
- src/utils/accounts.ts
> [HOT-FIX] Add GENEZIO_TOKEN to login a single command

- src/commands/deploy/nextjs.ts
- src/requests/getFrontendPresignedURL.ts
> Upload Next.js static files to S3

- src/commands/deploy/nextjs.ts
- src/commands/local.ts
- src/models/deployCodeResponse.ts
- src/requests/createFrontendProject.ts
> Add Next.js frontend CDN deployment

- src/commands/deploy/nextjs.ts
- src/constants.ts
> Setup required Open-Next environment variables on the functions

- src/commands/deploy/nextjs.ts
> Add large Next.js `public` folder warning

- src/commands/deploy/nextjs.ts
> Throw error if genezio.yaml is not provided for Next.js deployment in a CI environment

- src/commands/clone.ts
- src/commands/deploy.ts
- src/commands/deploy/genezio.ts
- src/commands/pull.ts
- src/genezio.ts
- src/requests/getPresignedURLForProjectCodePull.ts
- src/requests/getPresignedURLForProjectCodePush.ts
- src/utils/downloadProject.ts
- src/utils/file.ts
> added clone project

- src/commands/create/create.ts
- src/commands/create/interactive.ts
- src/models/commandOptions.ts
> Add Next.js, Express.js and Serverless to interactive `genezio create`

- src/commands/create/create.ts
> Implement `genezio create` for Next.js

- src/commands/create/create.ts
- src/genezio.ts
> Improve create messages and add `genezio create nextjs`

- src/commands/local.ts
Functions need to be available at `/` instead of `/.functions/:functionName`. For that, we want to communicate directly with the processes spawned by genezio and ensure they will use the same port for each run of `genezio local`.
> communicate directly with function processes and assure port consistency

- src/commands/create/create.ts
- src/commands/create/templates.ts
- src/genezio.ts
> Add `genezio create expressjs` functionality

- src/commands/pull.ts
- src/genezio.ts
`doAdaptiveLogAction` automatically handles errors or successes and updates the spinner accordingly.
```ts
export async function doAdaptiveLogAction<T>(message: string, action: () => Promise<T>) {
spinner.start(message);
return action()
.then((result) => {
spinner.succeed(`${colors.green(message)}`);
return result;
})
.catch((error) => {
spinner.fail(`${colors.red(message)}`);
throw error;
});
}
```
> Change manual adaptive log to automatic `doAdaptiveLogAction`

- src/yamlProjectConfiguration/v2.ts
> Default Genezio Functions `type` to `aws` for the moment

- src/commands/create/create.ts
- src/commands/create/templates.ts
- src/genezio.ts
> Add `serverless` to `genezio create`

- src/commands/create/create.ts
> Replace placeholders in the entrire filesystem for genezio create templates

- src/commands/deploy/nextjs.ts
- src/requests/getFrontendStatus.ts
> [next.js] Wait for CDN deployment before showing the application URL

- src/bundlers/node/genezioRuntimeHandlerGenerator.ts
-   [x] 🔥 Breaking change
In our runtime we would add cors headers automatically for all functions, this however poses a problem when we have express/faas functions that handle their own cors policies. To fix we stopped adding cors headers in the runtime and added cors headers in the runtimeHandler 
> added cors headers for each response

- src/commands/deploy/nextjs.ts
> Add `https://` to distribution URL

- src/commands/deploy/nextjs.ts
> Throw suggestive error if the user forgot to install the project NPM packages

- src/cloudAdapter/cluster/clusterAdapter.ts
- src/cloudAdapter/genezio/genezioAdapter.ts
- src/constants.ts
- src/requests/createFrontendProject.ts
The server now decides the frontend URL. The CLI should receive that value from the server and output it to the user.
> receive full frontend url from backend on deploy

- src/commands/deploy/nextjs.ts
> [next.js] Add race between Key press for skip and Frontend status deployment complete

- src/commands/deploy/nextjs.ts
Project deployment time (without waiting for CDN) before: **12.15s**
Project deployment time (without waiting for CDN) after: **10.35s**
The deployment is now 15% faster.
> Optimize Next.js deployment using parallelization

- src/commands/deploy/nextjs.ts
Take region into consideration when deploying Next.js apps. 
> Deploy Next.JS in multiple regions

- src/commands/deploy/nextjs.ts
Use a lighter version of AWS SDK in Next.js.
> Use lite aws sdk in nextjs

- src/genezio.ts
> Add process.stdin.unref at the end of CLI process

- src/commands/local.ts
This PR sends allows the local server to respond with functions information
> Add functions endpoint local

- src/cloudAdapter/genezio/genezioAdapter.ts
- src/commands/deploy/genezio.ts
- src/utils/file.ts
We were including the `.git` and `.github` folders in the zip. 
> Ignore .github files when zipping frontend and backend.

- package-lock.json
- package.json
> bump test interface

- src/cloudAdapter/cloudAdapter.ts
- src/cloudAdapter/genezio/genezioAdapter.ts
- src/commands/deploy/genezio.ts
- src/commands/deploy/nextjs.ts
- src/requests/createFrontendProject.ts
- src/requests/deployCode.ts
We need to be able to differentiate between projects using different technologies. `stack` is an array of strings that can contain all the technologies that a project is using. For now, we are able to differentiate only for Next.js.
> Add information in the request about what stack a project is using

- src/commands/deploy/command.ts
> [deploy/nextjs] Detect Next.js project based on if project contains "next" dependency

- src/commands/deploy/command.ts
> [bugfix] Check if package.json exists when deciding deploy type

- src/commands/deploy/nextjs.ts
> [nextjs] Remove polling from Next.js deployment as it's now done in the publish loading page

- src/commands/deploy/genezio.ts
Adding `typesafe` for project with Genezio classes to be able to take informed decisions in the dashboard.
> Add typesafe to the tech stack of the project

- src/commands/deploy/nextjs.ts
> [deploy/nextjs] Use default values when no genezio.yaml is provided in CI mode

- src/utils/logging.ts
> Redirect logging errors to stderr, while keeping the logs to stdout

- src/cloudAdapter/genezio/genezioAdapter.ts
> [bugfix] Await handle big element size error

- src/utils/configs.ts
> Skip TS lib check on deploy

- src/commands/deploy/command.ts
- src/commands/deploy/nextjs/assets.ts
- src/commands/deploy/nextjs/deploy.ts
- tests/commands/deploy/nextjs/assets.test.ts
> [nextjs] Add smart asset path pattern generation to avoid route collisions

- package-lock.json
- src/commands/deploy/genezio.ts
- src/commands/local.ts
- src/errors.ts
Catch deployment attempts with no units to be deployed and display an appropriate error message
> fail deploy for missing configuration

- src/commands/create/create.ts
> [create/nextjs] Account for `app` directory when changing the favicon

- src/constants.ts
> [bugfix] Use the correct bucket name for prod environment

- src/commands/deploy/nextjs/deploy.ts
> [nextjs] Increase public folder entries limitation

- src/commands/deploy/genezio.ts
- src/commands/local.ts
- src/requests/models.ts
- src/utils/scripts.ts
- src/utils/strings.ts
- tests/expandVariablesFromScript.test.ts
- tests/utils/scripts/expandVariablesFromScript.test.ts
This PR allows one single deploy command for fullstack projects with functions on the backend and a frontend.
To allow this, the user will be able to expand and inject environment variables at frontend build time in the `genezio.yaml`.
For both `genezio deploy [--frontend]` and `genezio local`, the following trick can be used in the `scripts` field:
```
build:
- ls -la
- VITE_HELLO_WORLD_FUNCTION_URL=${{functionHelloWorldApiUrl}} npm run build
start:
- npm install --silent
- VITE_HELLO_WORLD_FUNCTION_URL=${{functionHelloWorldApiUrl}} npm run dev --silent
```
The variables of format `${{functionCamelCaseNameApiUrl}}` will expand to the function URL - …
> Export api urls yaml

- src/commands/generateSdk.ts
> [generateSdk] Add option to specify sdk package name and version

- src/commands/deploy/nextjs/deploy.ts
> [nextjs] Add Next.js ISR service to projects

- src/genezio.ts
> [bugfix] Add `--path` for nextjs, backend and fullstack

- src/projectConfiguration/ts/config.ts
> [projectConfig/ts] Add a way to run the genezio.config.ts and extract the config

- src/functionHandlerProvider/providers/AwsFunctionHandlerProvider.ts
> Handle binary data in AWS handler

- src/commands/deploy/genezio.ts
> Fix problem when deploying a frontend would fail if no backend was deployed before

- src/commands/create/create.ts
- src/commands/create/interactive.ts
- src/commands/create/templates.ts
- src/genezio.ts
- src/models/commandOptions.ts
Please do not leave this blank. Add a small summary of the PR:
Enabling the creation of a nitro project by running `genezio create nitrojs`. 
!!!!We still need to create a getting-started repo for nitro, I used one of mine for this initial draft, needs to be changed before prod. 
> Add create nitro

- .github/workflows/release.yaml
> Add workflow that deploys @genezio/resources library

- src/commands/local.ts
- src/functionHandlerProvider/providers/AwsFunctionHandlerProvider.ts
- src/models/cloudProviderIdentifier.ts
> fixes cookies on functions

- src/commands/deploy/genezio.ts
We used to skip failed frontend builds without throwing an error. This lead to processes with just one failed frontend deployment returning exit code 0. My opinion is we should stop the deployment process on any failed operation and return a non zero exit code.
> throw error on failed frontend build

- src/commands/deploy/genezio.ts
- src/commands/deploy/utils.ts
- src/models/requests.ts
- src/projectConfiguration/yaml/models.ts
- src/projectConfiguration/yaml/v2.ts
- src/requests/authentication.ts
- src/requests/database.ts
- src/requests/function.ts
- src/requests/project.ts
- src/utils/requests.ts
- src/utils/scripts.ts
This PR adds `services.databases` to the yaml config.
The user can add a list of databases that will be created and linked to the project:
```
services:
databases:
- name: my-database-1
region: us-east-1
- name: my-database-2
```
> YAML - Deploy and link databases

- src/commands/deploy/genezio.ts
> Fix database region bug

- src/commands/create/create.ts
> [bugfix] Fix failing Next.js `genezio create`

- src/commands/deploy/genezio.ts
> [bug-fix] Check if frontend publish path exists after running the build script

- src/commands/deploy/genezio.ts
> Fix path for check if the frontend publish path exists

- src/commands/deploy/command.ts
> Add all extensions for next.config

- .github/workflows/release.yaml
> Remove publishing genezio/resources

- src/commands/deploy/genezio.ts
- src/commands/deploy/utils.ts
- src/commands/local.ts
- src/utils/scripts.ts
- src/utils/strings.ts
This PR adds support for using `frontend.environment` when testing locally with `genezio local`:
```
frontend:
environment:
VITE_HELLO_NAME: "name"
VITE_HELLO_API_URL: ${{ backend.functions.hello-blu.url }}
```
`${{ backend.functions.hello-blu.url }}` will expand to the corresponding local server `http://localhost:<port>/.functions/function-<function-name>`
Note: This PR also cleans unused code.
> [YAML] - Support yaml variables on genezio local

- src/commands/deploy/nextjs/deploy.ts
- src/commands/deploy/nextjs/edge.ts
Deploy Next.js edge functions as genezio functions instead of throwing an error. I want to merge this after the release on Monday.
> Deploy Next.js functions as genezio functions.

- src/commands/deploy/genezio.ts
- src/models/requests.ts
- src/projectConfiguration/yaml/v2.ts
- src/requests/integration.ts
This PR adds `services.email` to the yaml config.
The user can add a list of databases that will be created and linked to the project:
```
services:
email: true
```
> [YAML] - Add email integration

- src/commands/deploy/genezio.ts
- src/commands/deploy/nextjs/deploy.ts
- src/commands/deploy/utils.ts
`genezio deploy --env .env` did not work when deploying a Next.js application.
> Upload env vars during next.js deployment.

- src/cloudAdapter/cloudAdapter.ts
- src/cloudAdapter/cluster/clusterAdapter.ts
- src/cloudAdapter/genezio/genezioAdapter.ts
- src/commands/deploy/genezio.ts
- src/commands/deploy/nextjs/deploy.ts
- src/requests/deployCode.ts
> Add source repository for CLI deploys

- src/commands/deploy/nextjs/deploy.ts
> Display error and stop executing for invalid project names

- src/commands/deploy/genezio.ts
Fix pnpm for linux, for both functions and classes.
> Fix pnpm for linux

- src/commands/deploy/nextjs/deploy.ts
- src/commands/deploy/utils.ts
- src/commands/login.ts
- src/projectConfiguration/yaml/migration.ts
- src/telemetry/telemetry.ts
- src/utils/process.ts
> Add a method to detect CI environments

- src/commands/deploy/command.ts
- src/commands/deploy/nuxt/deploy.ts
Enable Nuxt function deployment, similar with Nitro and NextJS
> Enable nuxt function deployment

- src/commands/deploy/genezio.ts
- src/commands/deploy/utils.ts
- src/models/requests.ts
- src/projectConfiguration/yaml/models.ts
- src/projectConfiguration/yaml/v2.ts
- src/requests/authentication.ts
- src/utils/scripts.ts
This PR adds support for `services.authentication`:
```
services:
authentication:
database:
name: my-database-yaml
region: us-east-1
providers:
email: true
web3: true
google:
id: ${{env.GOOGLE_CLIENT_ID}}
secret: ${{env.GOOGLE_SECRET}}
```
> [YAML]- Add services.authentication

- src/projectConfiguration/yaml/models.ts
> Fix auth database type

- src/commands/deploy/nitro/deploy.ts
- src/commands/deploy/nuxt/deploy.ts
> [bugfix] Fix nitro and nuxt config function paths

- src/commands/deploy/utils.ts
- src/models/requests.ts
> Fix field name for enabling auth

- src/commands/deploy/utils.ts
- src/errors.ts
- src/models/requests.ts
- src/projectConfiguration/yaml/v2.ts
To enable Auth, the user can reference an already defined database with `name: my-database-yaml`.
```yaml
services:
databases:
- name: my-database-yaml
region: us-east-1
authentication:
database:
name: my-database-yaml
```
If the services.database.<name> is not defined, genezio will throw an error:
```
Error  Database my-database-yaml not found in the genezio.yaml configuration file. Please add it as following:
services:
databases:
- name: my-database-yaml
```
-   [x] New and existing unit tests pass locally with …
> Improve UX for enabling auth

- src/models/projectConfiguration.ts
- src/utils/scripts.ts
Enable support for:
```
frontend:
environment:
VITE_AUTHENTICATION_TOKEN: ${{ services.authentication.token }}
VITE_AUTHENTICATION_REGION: ${{ services.authentication.region }}
```
> Connect authentication to frontend

- src/commands/deploy/nitro/deploy.ts
- src/commands/deploy/nuxt/deploy.ts
Improved deployment logging for nuxt and nitro
> Improve logging

- src/commands/deploy/utils.ts
- src/models/requests.ts
Enforce `AuthenticationDatabaseType` for setting a database for auth.
export enum AuthenticationDatabaseType {
mongo = "mongodb",
postgres = "postgresql",
}
> Use the correct database type

- src/commands/create/create.ts
- src/commands/create/interactive.ts
Fixed some typos, and improved the logs of the genezio create CLI. 
> Fixed some typos and general flows

- src/utils/scripts.ts
> Return dev-fkt region if on dev environment

- src/commands/deploy/utils.ts
- src/models/requests.ts
- src/projectConfiguration/yaml/models.ts
- src/projectConfiguration/yaml/v2.ts
- src/requests/authentication.ts
- src/utils/scripts.ts
The genezio.yaml fields will be:
```
settings:
passwordReset:
redirectURL: https://${{frontend.awesome-capybara.subdomain}}.app.genez.io/auth/resetPassword
emailVerification:
redirectURL: ${{backend.functions.hello.url}}/auth/verifyEmail
```
In the future these fields will be extended to support email templates as such:
```
settings:
passwordReset:
redirectURL: https://${{frontend.awesome-capybara.subdomain}}.app.genez.io/auth/resetPassword
templatePath: <path-to-file>
subject: "subject"
emailVerification:
redirectURL: ${{backend.functions.hello.url}}/auth/verifyEmail
templatePath: <path-to-file>
subject: "subject"
```
-   [x] My code follows the contributor guidelines …
> Add auth email templates

- src/commands/deploy/utils.ts
- src/commands/local.ts
- src/utils/strings.ts
When running `genezio local` the following services are going to be spinned up:
- databases (if it's not created, the user will be prompted to confirm).
- authentication (if it's not created, the user will be prompted to confirm).
- email - it will just be created because it's not that sensitive.
After these are created, when running `genezio local` the database and authentication set up remotely will be used.
> Services on genezio local

- src/commands/bundle.ts
- src/commands/deploy/genezio.ts
- src/genezio.ts
- src/models/commandOptions.ts
This PR adds a hidden command `genezio bundleFunction` that will create the archive for a single function.
This command can be used like this:
```
genezio bundleFunction --functionName function-hello --output ./output
```
This method will be used in the Pulumi integration to deploy/change functions one by one.
> Add a command to bundle a single function

- src/commands/deploy/utils.ts
- src/models/requests.ts
- src/projectConfiguration/yaml/models.ts
- src/projectConfiguration/yaml/v2.ts
- src/requests/authentication.ts
- src/utils/scripts.ts
The feature is not usable like this because `subdomain` is not available in public templates
Reverts Genez-io/genezio#1331
> Revert "Add auth email templates"

- src/commands/deploy/nuxt/deploy.ts
Supporting older versions of Nuxt
> Supporting older versions of Nuxt

- src/commands/deploy/genezio.ts
- src/commands/deploy/utils.ts
- src/commands/local.ts
- src/models/requests.ts
- src/requests/integration.ts
- src/utils/environmentVariables.ts
- src/utils/scripts.ts
This PR brings some improvements and bug fixes for the services feature.
Each commit corresponds to an improvement/fix.
> Services improvs

- src/commands/deploy/genezio.ts
- src/commands/deploy/utils.ts
- src/commands/local.ts
This PR improves the DX experience for services when running `genezio local`.
The user will not be forced to create any resources remotely during local testing.
All the questions can be rejected and `genezio local` will still continue:
E.g.
```
? Project genezio-iac not found. Do you want to create it? no
Project genezio-iac not found and you chose not to create it.
Server listening on port 8083
%s Your local server is running and the SDK was successfully generated!
Functions Deployed:
- function-hello: http://localhost:8083/.functions/function-hello
Test your code at http://localhost:8083/explore
```
- …
> The local process should not force the user to deploy remote resources

- src/commands/deploy/utils.ts
Support the following format for `authentication.providers.google`:
```
providers:
email: true
web3: false
google:
clientId: ${{ env.GOOGLE_CLIENT_ID }}
clientSecret: ${{ env.GOOGLE_CLIENT_SECRET }}
```
> Enable ${{ env.KEY }} format for authentication.providers.google

- src/commands/deploy/utils.ts
This PR creates a the specified stage if it's not found remotely.
> Support stages for creating services

- src/commands/deploy/genezio.ts
- src/commands/deploy/utils.ts
- src/commands/local.ts
- src/utils/scripts.ts
This PR:
- Improves `genezio local` DX with logs and a question
- Updates the authentication providers if they changed in the genezio.yaml.
- Throws an error if project/authentication is not set, but `${{services.authentication.token/region}}` is used
- Removes old parsing methods for variables and replace them with `evaluateResource`.
> Small improvements and fixes on services

- src/commands/deploy/utils.ts
- src/utils/strings.ts
This PR:
- fixes the regex pattern to correctly match expressions like `${{backend.functions.my-hello.url}}`
- includes error message to help the user solve issues.
> Fix iac bugs

- src/commands/deploy/genezio.ts
- src/commands/deploy/utils.ts
- src/commands/local.ts
- src/projectConfiguration/yaml/v2.ts
Dynamically set the default database region to the `projectRegion`.
> Default database region is going to be the project region

- src/commands/deploy/genezio.ts
- src/commands/deploy/utils.ts
- src/commands/local.ts
- src/utils/environmentVariables.ts
A bug has been reported - the environment field was not correctly evaluated at `scripts.local`.
To prevent this, the following PR does the following:
- unifies the expanding variables codebase for all `frontend.scripts`.
- `backend.environment` was not using the `evaluatedResources` which is the correct method to expand environment variables and expression.
- `resolveEnvironmentVariable` is no longer used.
Each of these changes corresponds to a commit.
> Fix injecting environment variables

- src/commands/deploy/nuxt/deploy.ts
Inform user that genezio support only Nuxt 3+ projects.
> Notify about nuxt support

- src/bundlers/node/lambdaHandlerGenerator.ts
Return 400 status code when error instead of 500 and 200.
> GNZ-1340: Return 400 instead of 500 and 200

- src/commands/deploy/genezio.ts
- src/commands/local.ts
- src/utils/environmentVariables.ts
Fix the options.Local hardcoded to true.
> Fix options for genezio deploy and genezio local

- src/models/requests.ts
- src/projectConfiguration/yaml/models.ts
- src/projectConfiguration/yaml/v2.ts
- src/requests/database.ts
- src/utils/configs.ts
> [yaml/databases] Add `mongo-atlas` database type

- src/commands/deploy/utils.ts
> Fix helpful message typo

- src/commands/local.ts
> [local] Collect database URLs when more than one database is present

- package-lock.json
- package.json
> Bump package.json version

- src/functionHandlerProvider/providers/AwsFunctionHandlerProvider.ts
Instead of deciding in the handler how to handle error, we throw the error and let runtime decide.
> Let runtime decide how to handle js errors

- src/commands/login.ts
Killing Capy in CI environments because it takes space in build logs/test console logs and so on.
> Remove Capy from CI environments

- package-lock.json
- src/generateSdk/sdkWriter/basicFileWriter.ts
- src/requests/gaTrackEvent.ts
- src/utils/decorators/jsTsDecorators.ts
> Format the codebase

- package-lock.json
- src/cloudAdapter/cluster/clusterAdapter.ts
- src/cloudAdapter/genezio/genezioAdapter.ts
- src/utils/strings.ts
This PR ensures that subdomains longer than 63 characters will never be generated
> Sanitize frontend subdomain

- src/commands/deploy/genezio.ts
- src/functionHandlerProvider/providers/HttpServerHandlerProvider.ts
- src/models/projectConfiguration.ts
- src/projectConfiguration/yaml/models.ts
- src/projectConfiguration/yaml/v2.ts
I added the functionality to import an HTTP server (express, fastify, etc) without any changes. The only modification is in the yaml with `type: httpServer`
> Added node http server

- src/bundlers/node/nodeJsBundler.ts
- src/commands/deploy/genezio.ts
- src/commands/local.ts
- src/functionHandlerProvider/providers/AwsFunctionHandlerProvider.ts
- src/models/projectConfiguration.ts
- src/models/projectOptions.ts
- src/packageManagers/packageManager.ts
- src/packageManagers/pip.ts
- src/packageManagers/poetry.ts
- src/projectConfiguration/yaml/models.ts
- src/projectConfiguration/yaml/v2.ts
> [FAAS]: Add support python functions

- src/projectConfiguration/yaml/v2.ts
For SSR frameworks we are defining a custom component in the `genezio.yaml` to extend support for custom configuration.
The `genezio.yaml` will look like this:
```yaml
next:
path: ./app
packageManager: npm
scripts:
deploy:
build:
start:
environment: 
subdomain:
```
Note: This PR adds only the configs in the `genezio.yaml`, support for these are going to come in subsequent PRs.
> Define SSR frameworks in the config file

- src/commands/deploy/command.ts
- src/commands/deploy/nextjs/deploy.ts
- src/commands/deploy/utils.ts
- src/packageManagers/npm.ts
- src/packageManagers/packageManager.ts
- src/packageManagers/pnpm.ts
- src/packageManagers/yarn.ts
This PR:
* automatically install dependencies for nextjs projects
* adds a retry step for installing dependencies with `--legacy-peer-deps`
* throws friendly errors for common npm errors such as `invalid package.json` , `package not found`, and `missing package version`.
> Attempt to install dependencies with npm --legacy-peer-deps for nextjs

- src/packageManagers/pip.ts
- src/packageManagers/poetry.ts
Fix PackageManager for poetry and pip.
> Fix package manager interfaces for Python

- src/commands/deploy/genezio.ts
> fix path packages

- src/commands/deploy/utils.ts
> [yaml/auth] Enable Genezio-hosted MongoDB database in AUTH

- src/functionHandlerProvider/providers/HttpServerHandlerProvider.ts
Emit on server object instead of calling the handler directly.
> Emit on server object instead of calling the handler directly 

- src/bundlers/node/nodeJsLocalBundler.ts
- src/bundlers/utils.ts
- src/commands/deploy/genezio.ts
- src/commands/local.ts
- src/projectConfiguration/yaml/models.ts
- src/utils/getFunctionEntryFilename.ts
Add support for genezio local for FAAS Python.
> Add support for genezio local -> python

- src/packageManagers/pip.ts
- src/packageManagers/poetry.ts
- src/projectConfiguration/yaml/models.ts
- src/utils/detectPythonCommand.ts
Add detect start command for python
> Add detect python command

- src/commands/analyze/command.ts
- src/commands/analyze/frameworks.ts
- src/commands/analyze/utils.ts
- src/commands/create/create.ts
- src/commands/deploy/nextjs/deploy.ts
- src/commands/deploy/nuxt/deploy.ts
- src/commands/deploy/utils.ts
- src/genezio.ts
- src/models/commandOptions.ts
- src/projectConfiguration/yaml/v2.ts
Add `genezio analyze` command that automatically detects if the project is a next, nuxt, nitro, react with vite, react with CRA component.
The output is a functional, pretty standard `genezio.yaml`.
The implementation is naive and assumes the following:
* the root directory is the project directory (a `package.json` is mandatory in the root directory to analyze anything)
* the project is formed using a single component
Multiple-components projects and multiple configuration files (Dockerfile, go.mod, requirements.txt) will be supported in subsequent PRs.
-   [ ] …
> Add an analyze step for next, nuxt, nitro, vite, CRA

- src/bundlers/node/nodeJsLocalBundler.ts
- src/commands/deploy/genezio.ts
- src/commands/local.ts
- src/functionHandlerProvider/functionHandlerProvider.ts
- src/functionHandlerProvider/providers/AwsFunctionHandlerProvider.ts
- src/functionHandlerProvider/providers/HttpServerHandlerProvider.ts
- src/utils/getFunctionHandlerProvider.ts
- src/utils/scripts.ts
> Genezio local function provider refactoring and http server genezio local warning

- src/commands/deploy/command.ts
- src/commands/deploy/docker/deploy.ts
- src/commands/deploy/docker/utils.ts
- src/genezio.ts
- src/models/projectConfiguration.ts
- src/projectConfiguration/yaml/v2.ts
Detect container projects using the `genezio.yaml`.
The `--image <path-to-dockerfile>` will be used to set a custom path for the Dockerfile, if it's not set the current directory will be used.
> Detect container deployment

- src/bundlers/utils.ts
- src/functionHandlerProvider/providers/AwsFunctionHandlerProvider.ts
Move getLocalFunctionWrapperCode logic for python genezio local to work
> Move getLocalFunctionWrapperCode logic

- src/commands/analyze/command.ts
Change the publish directory from `build` to `dist` for vite components.
> Fix publish directory for vite projects

- src/commands/create/create.ts
The new template:
How the old one looked:
> [create/nextjs] Disable vercel to genezio transformation until fixed

- src/projectConfiguration/yaml/v2.ts
> [yaml] Add `redirects` and `rewrites` to the YAML configuration

- src/cloudAdapter/cluster/clusterAdapter.ts
- src/cloudAdapter/genezio/genezioAdapter.ts
- src/requests/createFrontendProject.ts
> [deploy/genezio] Send routing rules when creating frontend

- src/commands/analyze/command.ts
- src/commands/analyze/frameworks.ts
- src/commands/analyze/utils.ts
- src/projectConfiguration/yaml/v2.ts
Detect simple backend components such as express, fastify and serverless-http. This commit adds support only for js projects.
Detect backend components for javascript-only.
This PR detects the following components:
- an express backend
- a fastify backend
- aws-compatible serverless-http backends (works for everything that serverless-http supports)
Note 1: In a subsequent PR, we will add support for typescript projects - we have to decide how to detect the compiling process for ts.
Note 2: In a subsequent PR, we will add support for custom paths and multiple component projects.
-   [ ] I have updated …
> Detect backend components

- package.json
- src/commands/deploy/genezio.ts
- src/functionHandlerProvider/providers/HttpServerHandlerProvider.ts
- src/utils/getFunctionHandlerProvider.ts
> Add python httpServer handler

- package-lock.json
- src/functionHandlerProvider/providers/HttpServerHandlerProvider.ts
Add streaming for Flask/Django
> Add streaming for Flask/Django

- src/commands/local.ts
Disable genezio local with a friendly message on HttpServerPython
> Disable genezio local with a friendly message on HttpServerPython

- src/cloudAdapter/cloudAdapter.ts
- src/commands/deploy/genezio.ts
- src/generateSdk/generateSdkApi.ts
- src/generateSdk/utils/getAstSummary.ts
- src/models/astSummary.ts
- src/models/genezioModels.ts
- src/models/projectConfiguration.ts
- src/projectConfiguration/yaml/models.ts
- src/projectConfiguration/yaml/v2.ts
- src/requests/deployCode.ts
- src/utils/scripts.ts
- src/utils/strings.ts
Configure the function configuration via YAML file.
> Add custom parameters in YAML to configure function

- src/commands/analyze/command.ts
- src/commands/analyze/outputUtils.ts
- src/genezio.ts
- src/models/commandOptions.ts
`genezio analyze` will report the frameworks detected at stdout in a specified format.
This is useful for the following use cases:
* adding more information in our build environment/dashboard
* showing logs for the CLI users
* easy to generate documentation for our users
The supported formats are:
* json - this is useful in CI environments to programmatically get the output
* text - this is useful for logging purposes (the default used for our users)
* markdown - this is useful to create a documentation page (`genezio analyze --format markdown > architecture.md`)
* list
-   [ ] I have updated the …
> Report frameworks at stdout

- src/commands/deploy/utils.ts
> Remove log

- src/commands/deploy/docker/deploy.ts
Upload environment variables from `.env` file for serverless containers deployments.
The behaviour of env vars management is the same as for functions/classes/ssr:
- Upload the contents of the env vars file when `genezio deploy --env <envFile>` is executed.
- For `genezio deploy` detect if there is an `.env` and prompt the user to confirm if we should set the envs remotely.
> Upload environment files from a .env file

- src/commands/deploy/docker/deploy.ts
- src/commands/deploy/nextjs/deploy.ts
- src/commands/deploy/nuxt/deploy.ts
- src/commands/deploy/utils.ts
- src/models/projectOptions.ts
- src/projectConfiguration/yaml/v2.ts
Fix `uploadEnvVarsFromFile` method to support uploading environments variables defined in the `genezio.yaml` for components such as ssr frameworks and containers.
Up until now this was hardcoded only for `backend`.
This PR does the following:
* adds `container.environment` in `genezio.yaml`
* extends support for `uploadEnvVarsFromFile`
* fix uploading env vars for next, nitro, nuxt
> Add support for environment for containers and ssr frameworks

- src/commands/analyze/command.ts
- src/commands/analyze/utils.ts
- src/commands/deploy/command.ts
- src/commands/deploy/nextjs/deploy.ts
- src/commands/deploy/nuxt/deploy.ts
- src/commands/deploy/utils.ts
Be less intrusive when editing the `genezio.yaml`.
This PR changes the `util` functions used to add new components such as backend, frontend, ssr to:
* Save the comments from the `genezio.yaml`
* Add fields only if they are not set - if the fields are set in the `genezioyaml` and they are conflicting with what we "analyzed", we will prioritize the value from `genezio.yaml`
> Be less intrusive when writing back in the config file

- src/commands/analyze/command.ts
- src/commands/analyze/frameworks.ts
This PR adds logic to automatically detect new frontend frameworks such as Vue, Angular and Svelte.
> Detect Vue, Angular, Svelte

- src/commands/analyze/command.ts
- src/commands/analyze/frameworks.ts
- src/commands/analyze/utils.ts
- src/commands/deploy/utils.ts
Improve analyze to detect multiple component in fullstack projects.
> Support multiple components

- .github/workflows/ping-build-machine.yaml
-   [x] 🧑‍💻 Improvement (for developers)
This action will trigger a docker images rebuild job on `genez-io/genezio-build-machine`.
This is ping is authenticated with a fine-grained access token.
Documentation for this trick:
https://github.com/peter-evans/repository-dispatch
https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event
> Ping the build machine to sync with genezio cli merges

- .github/workflows/release.yaml
Automatically generate a new release with release notes on Github.
https://github.com/Genez-io/genezio/releases
> Automatically generate release notes

- src/functionHandlerProvider/providers/HttpServerHandlerProvider.ts
> Handle ASGI applications

- .github/workflows/ping-build-machine.yaml
- .github/workflows/release.yaml
This PR syncs GitHub actions improvements on the following:
* Automatically generate releases
* Ping the build machine
> Sync Github Actions

- src/functionHandlerProvider/providers/HttpServerHandlerProvider.ts
> Fix name module

- src/commands/analyze/command.ts
Instead of throwing an error if we don't detect anything, return `other` as backend and frontend frameworks.
Being less aggressive in this case lets the user configure his project on the dashboard side.
> Return other if we don't detect any relevant/supported framework

- src/commands/analyze/command.ts
- src/commands/analyze/constants.ts
- src/commands/analyze/frameworks.ts
- src/models/projectOptions.ts
- src/projectConfiguration/yaml/v2.ts
Instead of assuming `packageJson.main` or `index.mjs` is the entryfile name, search for it in a grep recursive style.
When the first suitable candidate is found, we stop the search.
We exclude uninteresting directories such as `.git`, `node_modules`.
> Improve getting the entryfile for backends

- src/commands/deploy/utils.ts
The log should reflect only the environment variables pushed, not all the ones found in the `.env`.
> Fix the environment variables uploaded log

- src/generateSdk/astGenerator/TsAstGenerator.ts
- src/generateSdk/generateSdkApi.ts
Clear possible AST Typescript resources to avoid an OOM error.
> Hack to fix memory issue in Typescript SDK generation.

- src/bundlers/node/nodeJsBundler.ts
> Avoid starving cpu and memory by running esbuild synchronously

- src/commands/analyze/command.ts
- src/commands/analyze/frameworks.ts
- src/commands/analyze/utils.ts
- src/commands/deploy/utils.ts
- src/projectConfiguration/yaml/v2.ts
Automatically detects databases such as postgres or mongo.
Adds them in the `genezio.yaml` to be provisioned IaC-drive.
> [Analyze] Automatically detect databases (postgres, mongo)

- package-lock.json
- package.json
- src/commands/analyze/agent.ts
- src/commands/analyze/command.ts
- src/commands/analyze/constants.ts
- src/commands/analyze/utils.ts
Based on `.env.example` or `.env.template` found in the repository, we are using an agent to try and help the user define them.
The help consists of:
- Defining default values for obvious or retrieved from comments such as `PORT = 3000`
- Provision services that are supported by Genezio such as postgres or database - `DATABASE_URL = ${{services.databases.mongo-db.uri}}` - this value is saved in `genezio.yaml`.
- Trying to point them to a documentation URL - this is prone to hallucation.
Note: This only works if an OPENAI_API_KEY is set in the environment.
-   [ …
> [Analyze] Detect and set environment variables

- src/commands/deploy/genezio.ts
Fix windows path for httpServer entryfile
> Fix windows path for httpServer entryfile

- src/commands/local.ts
Fix path httpServer local, when the entryfile is not locate in root directory.
> Fix path httpServer local

- src/commands/deploy/genezio.ts
> improve cron terminal output

- src/genezio.ts
> Log improvement version

- .github/workflows/ping-build-machine.yaml
- .github/workflows/release.yaml
-   [X] 🧑‍💻 Improvement
Improve CI/CD by enabling a sync builds between the CLI and the build machine.
> Sync cli releases and build machine redeployments and notify the team

- src/commands/analyze/agent.ts
- src/commands/analyze/command.ts
- src/genezio.ts
> Fix analyze logs

- src/commands/deploy/nextjs/deploy.ts
> Handle cache nextjs

- src/commands/deploy/nextjs/deploy.ts
> Fix path for next server

- src/commands/deploy/nextjs/deploy.ts
Ignore typescript type checking in cache file.
> Ignore typescript checking in cache handler.

- package-lock.json
- src/cloudAdapter/cloudAdapter.ts
- src/commands/deploy/genezio.ts
- src/commands/deploy/nextjs/deploy.ts
- src/commands/local.ts
- src/models/projectConfiguration.ts
- src/projectConfiguration/yaml/v2.ts
Add HttpServer wrappers - genezio local
> Add HttpServer Wrappers - genezio local

- src/commands/local.ts
- src/utils/scripts.ts
> fix iac function url

- src/commands/analyze/command.ts
- src/commands/analyze/frameworks.ts
- src/commands/deploy/genezio.ts
Handle pyproject.toml if requirements.txt doesn't exist.
> Handle pyproject.toml

- src/commands/analyze/frameworks.ts
This PR fixes the following bug:
```yaml
backend: ./server
functions:
entry: ./server/index.js
```
It should be:
```
```yaml
backend: ./server
functions:
entry: ./index.js
```
> Fix relative path for reading entry files

- src/commands/analyze/utils.ts
- src/commands/deploy/utils.ts
This PR makes sure we are correctly addind new databases in the yaml:
- It generates a new name only if the default databases is already created (default means my-mongo, my-postgres)
- It add a new database in the yaml only if the database type is different - i.e. it **doesn't** append a second mongo if the first database is mongo. It **does** append a postgres, if the first database is mongo.
> Analyze fix database

- src/commands/analyze/command.ts
- src/commands/analyze/frameworks.ts
- src/commands/deploy/command.ts
- src/commands/deploy/nestjs/deploy.ts
- src/commands/deploy/utils.ts
- src/models/projectOptions.ts
- src/projectConfiguration/yaml/v2.ts
Add NestJs support
https://nestjs.com/
> Add NestJs support

- .github/workflows/ping-build-machine.yaml
- .github/workflows/release.yaml
Trigger build machine redeployments on git tag push rather than push on `main`.
> Fix gha release

- src/commands/deploy/nestjs/deploy.ts
> Resolve nestjs edit code bug

- src/commands/analyze/command.ts
> Give nestjs a higher priority

- src/commands/deploy/genezio.ts
- src/commands/local.ts
- src/utils/jsProjectChecker.ts
Remove check experimental decorators
> Remove check experimental decorators

- package-lock.json
- package.json
- src/commands/local.ts
> temporary remove test interface

- package-lock.json
- package.json
- src/commands/local.ts
> update test interface component

- package-lock.json
- package.json
> update test interface

- package-lock.json
- package.json
> update Package Json version

- src/commands/deploy/nextjs/deploy.ts
> start.js becomes start.mjs

- package-lock.json
- package.json
- src/commands/local.ts
This reverts commit f3a9079cc04a5b7aada7a1d39b20bf5899b3f165.
> Revert "update test interface component"

- src/commands/deploy/genezio.ts
> sync cron jobs after frontend deploy

- package-lock.json
- package.json
> update test interface version

- package-lock.json
- package.json
- src/commands/local.ts
Context: we want to push the users to test their functions from postman instead of our test interface because our test interface is not as robust and effective as postman. As such, the new version of the test interface will handle functions simillar to how we handle http methods and alert the user to use Postman instead. If the user doesn't have any classes then the test interface will not be available all togheter. It will be shown only if the user has a minimum of one class
-   [ ] New and existing unit tests pass locally with my …
> test interface not available if no classes found

- src/commands/analyze/command.ts
- src/commands/deploy/docker/deploy.ts
- src/commands/deploy/genezio.ts
- src/commands/deploy/nestjs/deploy.ts
- src/commands/deploy/nextjs/deploy.ts
- src/commands/deploy/nuxt/deploy.ts
- src/commands/deploy/utils.ts
This PR does a bit of refactoring to enable `services` for ssr frameworks:
```
name: genezio-nextjs-getting-started
yamlVersion: 2
services:
databases: ...
nextjs:
path: .
packageManager: npm
scripts:
deploy:
- npm install
```
> Enable services configuration for ssr frameworks

- src/commands/analyze/agent.ts
- src/commands/analyze/command.ts
- src/commands/analyze/frameworks.ts
- src/commands/analyze/utils.ts
- src/commands/deploy/command.ts
- src/commands/deploy/utils.ts
This PR makes an improvement on reporting the environment variables to the dashboard.
Now every set of environment variables is mapped to the corresponding component.
The mapping is done using the `path` which must be the same for the component and for the `.env.example` file.
```
export type FrameworkReport = {
backend?: BaseComponent[];
frontend?: BaseComponent[];
ssr?: BaseComponent[];
services?: FrameworkReportService[];
};
export type BaseComponent = {
component: string;
path?: string;
environment?: ProjectEnvironment[];
};
```
This is a breaking change for the frontend because it updates the objects passed to the dashboard - this PR should be merged with it's …
> [BREAKING CHANGE] Enhance genezio analyze env vars

- src/commands/deploy/command.ts
- src/commands/deploy/nestjs/deploy.ts
Fix nestjs path for fullstack logic
> Fix nestjs path for fullstack logic

- src/commands/analyze/command.ts
- src/commands/analyze/utils.ts
- src/commands/deploy/command.ts
- src/commands/local.ts
- src/models/projectConfiguration.ts
- src/utils/scripts.ts
> Improve iac and analyze for fullstack nest and frontend projects

- src/commands/deploy/command.ts
> Deploy a classic component only once

- src/commands/analyze/utils.ts
This fix corresponds to the bug discovered via integration tests:
https://github.com/Genez-io/genezio-tests/actions/runs/12363642102
> Use function names instead of indexes

- src/commands/analyze/frameworks.ts
> Ignore React Native projectS

- src/commands/deploy/command.ts
- src/commands/deploy/zip/deploy.ts
- src/genezio.ts
- src/models/commandOptions.ts
Add an option to the deploy command that allows you to deploy a genezi project already built.
> Add option to deploy from zip

- src/commands/local.ts
Remove the CORS configuration.
Context: In the local environment, we configure CORS with a wildcard (`*`) to simplify development. However, when the application is deployed, the user is responsible for setting the appropriate CORS configuration themselves. This current setup may lead to issues, such as a conflict when the wildcard (`*`) is set twice, resulting in errors.
> Remove setting cors | genezio local

- src/commands/deploy/command.ts
To allow injecting artefacts such as a deployment ordering is needed:
```
backend:
functions:
- name: express
nextjs:
...
environment:
NEXT_PUBLIC_API_URL_EXPRESS: ${{ backend.functions.express.url }}
```
This PR naively sorts deployable component into backend frameworks first, then frontend frameworks.
In a subsequent task, we will dynamically create a deployment order based on the dependencies defined in the `genezio.yaml`.
> Softly order the deployable components

- package-lock.json
- src/commands/deploy/command.ts
- src/commands/deploy/nextjs/deploy.ts
- src/commands/deploy/utils.ts
Handle Nextjs fullstack applications
> Handle Nextjs fullstack applications

- src/utils/configuration.ts
> validate cron decorator variable

- src/commands/deploy/utils.ts
This PR improves random naming for new projects:
- use the repository name
- if that is already used, we will concatenate a few random characters to the repository name
- if a repository is not available at all, we use package.json name
- if a package.json is not available at all, we randomly generate it
> GNZ 2182 - Genezio analyze name improv

- src/commands/analyze/command.ts
- src/commands/deploy/utils.ts
- src/genezio.ts
- src/models/commandOptions.ts
Let the user customize the name and region of the project to avoid dynamic questions in the CI environment:
```
genezio analyze --name project-name --region eu-central-1
```
> Let the user customize name and region from command line

- src/commands/analyze/command.ts
Adding start scripts for the frontend components will enable `genezio local` to start the project in a fullstack manner.
> GNZ-2183 Add start script for frontend components

- src/commands/local.ts
> Improvement local remix

- src/functionHandlerProvider/providers/AwsFunctionHandlerProvider.ts
- Add validation for undefined handler responses
- Ensure headers object exists before cookie processing
- Add type checking for cookies array
> fix: Add null checks for handler response in Nodejs AWS provider

- src/commands/local.ts
- src/functionHandlerProvider/functionHandlerProvider.ts
- src/functionHandlerProvider/providers/AwsFunctionHandlerProvider.ts
Fix import module py and show stacktrace error on faas.
> fix: import module py on faas wrapper

- src/commands/local.ts
- src/models/projectOptions.ts
- src/utils/scripts.ts
This PR exposes the local URL for nestjs at `genezio local` as an env var `VITE_API_URL_NESTJS`:
```
Environment variables injected for frontend.scripts.local: {"VITE_API_URL_NESTJS":"http://localhost:3000"}
```
This is for starting a fullstack app (nestjs and react) with `genezio local` in a iac manner.
> Expose localhost URL for nestjs for running locally

- src/commands/analyze/command.ts
- src/commands/analyze/utils.ts
This is a second attempt to remove ssr frameworks if they are detected alongside backend functions.
I tried to do this in this PR -https://github.com/Genez-io/genezio/pull/1650 - but I introduced a flaky behaviour (sometimes the ssr framework was ignored, sometimes it was added). The flaky behaviour is detected in the integration tests for the analyze step.
> Remove ssr if detected alongside backend functions

- src/cloudAdapter/cloudAdapter.ts
- src/commands/deploy/docker/deploy.ts
- src/commands/deploy/genezio.ts
- src/commands/deploy/zip/deploy.ts
- src/generateSdk/generateSdkApi.ts
- src/generateSdk/utils/getAstSummary.ts
- src/models/astSummary.ts
- src/models/genezioModels.ts
- src/models/projectConfiguration.ts
- src/projectConfiguration/yaml/v2.ts
- src/requests/deployCode.ts
- src/utils/configuration.ts
- src/utils/decorators/baseDecoratorExtractor.ts
This PR adds the option to change your max concurrent instances for a function
> add max concurrent instances

- src/commands/analyze/command.ts
- src/commands/analyze/frameworks.ts
Enable analyze amber. 
Getting started: https://github.com/Genez-io/ember-getting-started
> feat: enable analyze amber

- src/commands/analyze/command.ts
- src/genezio.ts
- src/models/commandOptions.ts
This PR:
- prevents `genezio analyze` from overwriting a present `genezio.yaml`. An imported project with a `genezio.yaml` will remain untouched.
- adds a way to allow the user to forcefully overwrite the configuration file - in case it's needed.
> Do not overwrite a present genezio.yaml after analyzing

- src/commands/deploy/genezio.ts
- src/commands/deploy/utils.ts
- src/commands/local.ts
- src/utils/environmentVariables.ts
> Revert "Propagate the env file correctly"

- src/commands/local.ts
show logs on genezio local - python wsgi
the problem it solves: if i use an application like flask(wsgi), i can't see the logs
> fix: show logs on genezio local - python wsgi

- src/commands/analyze/frameworks.ts
- src/commands/deploy/command.ts
- src/models/projectOptions.ts
- Added support for detecting Streamlit dependencies in `pyproject.toml`
- Maintains existing `requirements.txt` check
- Implements early return pattern for better performance
> feat: add pyproject.toml support for Streamlit detection

- src/cloudAdapter/cloudAdapter.ts
- src/commands/deploy/docker/deploy.ts
- src/commands/deploy/genezio.ts
- src/commands/deploy/zip/deploy.ts
- src/generateSdk/generateSdkApi.ts
- src/generateSdk/utils/getAstSummary.ts
- src/models/astSummary.ts
- src/models/genezioModels.ts
- src/models/projectConfiguration.ts
- src/projectConfiguration/yaml/v2.ts
- src/requests/deployCode.ts
- src/utils/configuration.ts
- src/utils/decorators/baseDecoratorExtractor.ts
- src/utils/decorators/decoratorTypes.ts
- src/utils/scripts.ts
- src/utils/strings.ts
This adds the `persistent` flag in the `genezio.yaml` to enable a function to run indefinitely (long-running).
> Add longRunning/Persistent function flag

- src/models/projectOptions.ts
chore: update default Python runtime to 3.13
> chore: update default Python runtime to 3.13

- src/bundlers/node/nodeJsBundler.ts
- src/commands/local.ts
Normally, we should not throw `invalid node version" because the `genezio.yaml` file is a typed and checked.
The only edge case for this case is when the `backend.language.runtime` is undefined - I think we can use the default value then.
> Fix invalid node options error

- src/genezio.ts
Update the port option description to clarify its purpose for testing genezio classes locally. This change makes it more intuitive for users to understand what the port setting is used for.
> chore: update port description for local testing

- src/projectConfiguration/yaml/v2.ts
Improve the genezio.yaml schema to enforce `handler` when is mandatory.
> Improve warnings related to functions[].handler

- src/projectConfiguration/yaml/v2.ts
> Revert "Improve warnings related to functions[].handler"

- src/commands/deploy/genezio.ts
fix: handle multiple functions
> fix: handle multiple functions

- src/commands/analyze/command.ts
- src/commands/deploy/docker/deploy.ts
- src/commands/deploy/genezio.ts
- src/commands/deploy/nestjs/deploy.ts
- src/commands/deploy/nextjs/deploy.ts
- src/commands/deploy/nuxt/deploy.ts
- src/commands/deploy/remix/deploy.ts
- src/commands/deploy/streamlit/deploy.ts
- src/commands/deploy/zip/deploy.ts
- src/commands/local.ts
- src/models/projectConfiguration.ts
- src/projectConfiguration/yaml/models.ts
- src/projectConfiguration/yaml/v2.ts
- src/utils/getFunctionHandlerProvider.ts
To define a persistent function use the following `genezio.yaml` config:
```
functions:
...
type: persistent
```
For ssr (nextjs | nuxt | nestjs | remix | streamlit) you can also defined `type: persistent`:
```
nextjs:
type: persistent
```
For containers it's the same.
```
containers:
type: persistent
```
> Update persistent configuration

- src/commands/deploy/utils.ts
- src/requests/getProjectInfoByName.ts
> Do not throw if project is not found

- src/requests/axios.ts
> handle forbidden requests

- package-lock.json
- src/commands/local.ts
> fix: ssr path genezio local

- package-lock.json
- package.json
- src/commands/deploy/docker/deploy.ts
- src/commands/deploy/genezio.ts
- src/commands/deploy/nestjs/deploy.ts
- src/commands/deploy/nextjs/deploy.ts
- src/commands/deploy/nuxt/deploy.ts
- src/commands/deploy/remix/deploy.ts
- src/commands/deploy/streamlit/deploy.ts
- src/commands/deploy/utils.ts
- src/commands/local.ts
- src/requests/axios.ts
- src/utils/environmentVariables.ts
> Release v 3.2.3

- src/commands/deploy/utils.ts
An admin that attempts to deploy a project with a database in `services.database` will trigger the following behaviour:
- a new database will be created in the admin account
- an attempt to link the database will be tried
- the attempt will fail with "a database with the same name is already linked to this project"x
To take into account that owners can link databases to a project and admins can use these databases, the logic for the IaC should be updated as following:
- verify if the database set in the yaml is already linked in the project - if yes, use it.
- if no, verify if the database is already created in the account of the one who is deploying - if yes, proceed …
> Before creating a database, verify if it was linked by an owner

- src/commands/list.ts
- src/genezio.ts
- src/models/commandOptions.ts
Support `--format json` for `genezio list` to be able to integrate this command in CI/CDs. A use-case for this is to dynamically get CloudDeploymentIDs based on the project name.
> Enhance genezio list

- package-lock.json
- package.json
- src/commands/list.ts
- src/genezio.ts
- src/models/commandOptions.ts
-   [x] 🍕 Release v3.2.7
Release v3.2.7 to support `genezio list --format json`.
> Release v3.2.7

- src/commands/deploy/genezio.ts
- src/commands/local.ts
- src/generateSdk/sdkSuccessReport.ts
- src/generateSdk/sdkWriter/sdkWriter.ts
- src/models/projectConfiguration.ts
- src/projectConfiguration/yaml/models.ts
- src/projectConfiguration/yaml/v2.ts
- src/utils/getFunctionHandlerProvider.ts
Add `python-asgi` as a new language.
> Add custom image for python-asgilinux

- .github/dependabot.yaml
- package-lock.json
- package.json
> Downgrade express

- src/commands/database.ts
- src/genezio.ts
- src/models/commandOptions.ts
- src/models/requests.ts
- src/requests/database.ts
> Add genezio database to manage dedicated databases
