src/index.ts

Add command to display the logged in account in CLI.
If no account is in the keychain, displays `Unauthorized. You are not logged in.`.

Add account display command

---

examples/blockchain/README.md
examples/hello-world/README.md
examples/todo-list/README.md
src/commands.ts
src/index.ts
src/localEnvironment.ts
src/models/projectConfiguration.ts
src/variables.ts

Bugs fixed:
* GNZ-250 - `genezio` will show help and return code 0 when executed without any options/commands
* GNZ-251 - Checked examples/README.md to contain `npm install` where needed
* GNZ-252 - Added nice info for unknown commands/options when using `genezio`
* GNZ-277 - Exit gracefully when user is not logged and executes `genezio local`
* GNZ-278 - Added check if classes exists at the path mentioned in `genezio.yaml`. Affects `genezio local`, `genezio deploy` and `genezio addClass`.

Fixes for genezio usage

---

src/requests/axios.ts
src/requests/deleteProject.ts
src/requests/deployCode.ts
src/requests/generateSdk.ts
src/requests/getFrontendPresignedURL.ts
src/requests/getPresignedURL.ts
src/requests/getProjectInfo.ts
src/requests/listProjects.ts

Send the CLI version in HTTP request headers to the backend and react when the backend says that the version is not supported.

GNZ-416: Message to update CLI if version is not supported anymore.

---

src/bundlers/javascript/nodeJsBundler.ts

The error was due to the fact that the paths within `#copyNonJsFiles` were all separated by '/', regardless of the platform. When `filePath.path.split` was applied, nothing changed to the paths, and the following `folders.pop();` deleted the path altogether. Afterwards, when `cp` tried to copy a file to an inexistent folder, it threw an error

Fix Windows error when deploy/local

---

src/localEnvironment.ts
tests/projectConfiguration.test.ts

`2/5 * * * *` is a non-standard cron string as per https://crontab.guru/#2/5_*_*_*_* . The `node-cron` library doesn't support this format, although both Windows, Linux and AWS Lambda support it. The easiest solution was to detect these strings when deploying locally, and convert them to standard cron strings that have the same meaning:
`2/5 * * * *` == `2-59/5`
Rinse and repeat for all fields.

Convert non-standard crons to standard crons for local deployment

---

.github/workflows/unit-test.yaml
package.json

I fixed `jest` picking on some Angular unit tests from the `examples` folder (this behavior is reproducible only locally because in the CI/CD we are not fetching the submodules).
The CI/CD was run twice at every PR (once for the generic `push` trigger and once for the `pull_request` trigger). I fixed it by explicitly running the action only for pushing to `dev` or `master`. For all of the other pushes, the action will be triggered from the `pull_request` trigger.

Improve unit tests CI/CD

---

src/commands/deploy.ts
src/utils/file.ts

`fs.rmdir` is deprecate. Node is advising to use `fs.rm` instead.
Manually

GNZ-816 Fix deprecation warning related to `fs.rmdir`

---

.github/dependabot.yaml

Force update on both `package.json` and package-lock.json`.
Right now, there are commits where only `package-lock.json` was modified and that is not persistent to `npm install`.
The `dependabot.yaml` has to be changed on master, otherwise, the changes are not taking effect.

[HOT FIX ] Update dependabot.yaml

---

src/errors.ts
src/generateSdk/astGenerator/DartAstGenerator.ts

Created a list with all the types/errors that genezio AST is not currently supporting.
If a type is on this list, the tool will throw an error.
The list was created by looking into the official documentation from [dart:core ](https://api.dart.dev/be/180791/dart-core/dart-core-library.html#classes)
Manually by running genezio locally.

GNZ-774 Throw an error for unsupported built-in dart:core types

---

src/bundlers/dart/dartBundler.ts

`aws_lambda_dart_runtime` 1.0.3 is no longer supported for Dart 3.0. Bump the dependency version to ensure program compiles.

Bump `aws_lambda_dart_runtime` to ^1.1.0 to make it work with Dart 3

---

src/bundlers/javascript/nodeJsBundler.ts
src/bundlers/javascript/nodeJsDependenciesBundler.ts
src/bundlers/typescript/nodeTsBundler.ts
src/bundlers/typescript/nodeTsDependenciesBundler.ts

Temporarily, we've removed the logic that selects only the dependencies needed by a class because of some bugs with CommonJS and ESModule. However, this caused a problem with the binary dependencies. I was using the wrong path in the bundler.

Use the original path instead of using the path of the temp folder path

---

package-lock.json
package.json
src/bundlers/dart/dartBundler.ts
src/bundlers/dart/localDartBundler.ts
src/commands/deploy.ts
src/commands/local.ts
src/utils/file.ts

Previously, there were a lot of temporary folders created if dart projects were deployed using `genezio deploy` or if any kind of project was tested with `genezio local`.
Fixed this by removing all those folders in case of errors.
Also, updated the name of the temporary folders to start with `genezio-` prefix, instead of `foo-`.

GNZ-817 Auto-delete `/tmp` folders for dart projects and `genezio local`

---

src/bundlers/node/nodeJsBundler.ts

In `genezio local` we copy all available dependencies once, so a list of dependencies is not needed in development mode.

Generate dependency list only when `genezio deploy` is ran

---

src/bundlers/node/typeCheckerBundler.ts
src/utils/configs.ts

If a tsconfig file does not exist in the project, the code would try to write the default tsconfig content to the file, but we did not wait for its completion.
Moreover, we had to use target "ES2020" in tsconfig to have support for `import.meta`.

Wait until the ts config file is written successfully

---

src/generateSdk/templates/nodeSdkTs.ts

Typescript will return an error if we use `fetch` in a NodeJS client. To avoid that, we tell typescript to ignore that line.

Ts ignore fetch line in SDK

---

package-lock.json
package.json
src/bundlers/node/dependencyInstaller.ts
src/bundlers/node/nodeJsBundler.ts

Running multiple npm install commands at once can lead to race conditions. I have implemented a singleton class that handles all installs and orders them sequentially.

Run all `npm install` commands sequentially

---

src/commands/init.ts
tests/commands.test.ts

When we initialize a new project with `genezio init`, we should create a new folder that has the name of the project. Also, we should validate that the name is correct.

GNZ-989: Fix genezio init bugs

---

src/bundlers/node/nodeJsBinaryDependenciesBundler.ts

We were assuming that `node_modules/<module/package.json` always exists. I've added a check because this was not true for `.prisma/client`.

Don't assume that package json exists

---

src/bundlers/node/dependencyInstaller.ts
src/bundlers/node/nodeJsBundler.ts
src/bundlers/node/typescriptRequiredDepsBundler.ts
src/commands/addClass.ts
src/commands/deploy.ts
src/commands/local.ts

If you create a project with `genezio init` and you add a typescript class, you will receive an error because @types/node module is missing. We install it during `genezio local` or `genezio deploy`.

Install @types modules that are required by TS if they are not already installed.

---

package-lock.json
src/bundlers/node/lambdaHandler.ts

Change the lambda handler in order to support the Sentry integration. When an error occurs, it will try to load the @sentry/node module. It will pass on silently if the integration is not active.

change handler for sentry integration

---

src/generateSdk/astGenerator/TsAstGenerator.ts
src/generateSdk/sdkGenerator/TsSdkGenerator.ts

Replace backslashes (`\`) with forward slashes (`/`) in import paths. This generated a bug on windows which would use invalid paths.

replace all backslashes in path with forward slashes

---

src/models/projectConfiguration.ts

- [x ] 🐛 Bug Fix
Solved a bug that would've broken the test-interface for deployments with older versions of the CLI. The AST version was hardcoded in the backend. This fix sends the AST version in the request payload.

add ast version to deploy payload

---

src/bundlers/node/nodeJsBundler.ts
src/commands/deploy.ts
src/genezio.ts
src/models/commandOptions.ts
src/models/environmentVariables.ts
src/requests/setEnvironmentVariables.ts
src/utils/file.ts

This PR adds the following `--env <envFile>` to `genezio deploy`.
This will load the environment variable from the given file. If no filename is given, the default `env` is going to be used. 
With this feature in place, there is no need to use `dotenv` anymore to load environment variables.
Both for `genezio local` and `genezio deploy` --env <envFile>` loads the env vars.
Any file that starts with `.env` will not be bundled.

GNZ-927 Add --env <envFile> to `genezio deploy`

---

src/commands/local.ts
src/utils/file.ts

This PR changes `\n` to `EOL` which is os-specific.

Fix newline to be os-specific when reading from files

---

src/bundlers/node/nodeJsBundler.ts

Require using relative paths was broken due to esbuild not supporting `createRrequire` (we used to textually replace `require` with `createRequire` to be able to use this in ESM context). Because required code couldn't be bundled, paths became incorrect and would generate errors.
Solution was to remove support for require with relative paths. Users will still be able to use `require` to import from `node_modules`. For relative paths, we will output an error suggesting to switch to import statements.

Gnz 1030 bundle issue

---

src/bundlers/node/lambdaHandler.ts

Updated handler to catch errors sent inside a setTimeout callback. Also added Sentry logic in more places, to be able to catch and send error sent in async functions.

catch errors in setTimeout and send async errors to sentry dashboard

---

src/generateSdk/astGenerator/TsAstGenerator.ts
src/generateSdk/sdkGenerator/TsSdkGenerator.ts
src/models/genezioModels.ts

Added support in genezio AST for typescript indexed mapped type (e.g. syntax like `{[key: string]: string}`

add index mapped type support

---

src/generateSdk/astGenerator/TsAstGenerator.ts

This provides better error handling on AST generation for typescript. There should be no more uncaught errors when a user declares an unsupported type. Instead, an error will indicate which declaration is the problem and will provide a link to the documentation with supported declaration types.

error handling for typescript ast

---

src/commands/deploy.ts
src/commands/local.ts
src/utils/file.ts

Remove contents of temp folder which stores the npm sdk before building a new version. There were certain edge cases where one would need to manually delete the folder in order to get a working sdk

clean temp folder before generating a new sdk

---

src/generateSdk/sdkGenerator/TsSdkGenerator.ts

SDK generation on windows from root of monorepo with decorators failed because of different file separators

fix monorepo windows sdk bug

---

src/commands/deploy.ts
src/commands/generateSdk.ts
src/commands/local.ts
src/models/yamlProjectConfiguration.ts
src/utils/configuration.ts

Instead of having a `genezio.yaml` in the root of the workspace and two `genezio.yaml`s in the server and client, now we are having only one `genezio.yaml` in the root that contains information about both server and client.
I removed some of the code that was parsing the root `genezio.yaml` in a different way than the other two yamls. Also, I've modified the writeToFile method that was having different behaviours based on what type of yaml it is.

Only one genezio.yaml configuration file for workspaces.

---

src/bundlers/node/nodeJsBundler.ts

We don't support relative requires in genezio. Because of this we added a plugin in esbuild that checks if user is using a relative require and gives and informative error if it finds one. The problem occured when a dependency (one that is using a relative require) was bundled together with the user's code. This can happen if the user has installed the dependency as a `devDenpendecy` or if the dependency is not found in `package.json` but it exists in `node_modules` (we are using `nodeExternalsPlugin` to avoid bundling all the dependencies).
Now, we are checking if the file that will be bundled comes from `node_modules` folder and if this is the case, we don't check for relative requires anymore.

Ignore files that come from 'node_modules' when checking for relative requires

---

src/commands/generateSdk.ts
src/generateSdk/generateSdkApi.ts
src/generateSdk/sdkGenerator/DartSdkGenerator.ts
src/generateSdk/sdkGenerator/JsSdkGenerator.ts
src/generateSdk/sdkGenerator/KotlinSdkGenerator.ts
src/generateSdk/sdkGenerator/PythonSdkGenerator.ts
src/generateSdk/sdkGenerator/SwiftSdkGenerator.ts
src/generateSdk/sdkGenerator/TsSdkGenerator.ts
src/generateSdk/sdkGeneratorHandler.ts
src/models/genezioModels.ts

The index file used for the node_module version of the SDK was problematic in the old context of generating the SDK. This PR assures that classes with no JSON-RPC methods are not included in the SDK or index file, and the index file will not be added in the old way of generating the SDK.

remove index from old sdk generation and skip classes without jsonrpc methods

---

src/telemetry/sdk/analyticsHandler.sdk.ts
src/telemetry/telemetry.ts

We want to send the node version as an analytic because we want to know when is safe to drop an old (deprecated) NodeJS version.

Add `nodeVersion` field to the genezio-analytics request

---

src/commands/local.ts

During `genezio local`, if a class fails and crashes, the next request will restart the class process. However, before this fix, the env variables associated with that class where not passed correctly to the newly started process.

  Restarting process does not load the env variables

---

src/utils/configuration.ts

When parsing the cwd files hierarchy to parse the files for genezio decorators we should skip directories.

Filter directories when parsing the files hierarchy for decorators

---

src/commands/deploy.ts
src/genezio.ts
src/models/commandOptions.ts
src/models/yamlProjectConfiguration.ts

This change adds a new `--subdomain` option flag. This option overrides the `genezio.yaml` configuration file subdomain entry.

Add `--subdomain` option for genezio deploy

---

src/cloudAdapter/cloudAdapter.ts
src/cloudAdapter/genezio/genezioAdapter.ts
src/commands/deploy.ts
src/utils/calculateBiggestProjectFiles.ts

The `calculateBiggestFiles` function was having `any` types for it's parameters. That introduced some bugs because the expected typing was not the actual typing in other contexts. This change fixes it.

Add `calculateBiggestFiles` typing

---

src/packageManagers/npm.ts
src/packageManagers/pnpm.ts
src/packageManagers/yarn.ts

This change enables users who use `yarn` to install the production `sdk` which is stored in a private npm repository (needs auth).

Add private repository authentication (scoped registries) for yarn v2 and above

---

src/commands/deploy.ts
src/commands/link.ts
src/commands/local.ts
src/generateSdk/templates/packageJson.ts
src/generateSdk/utils/compileSdk.ts
src/genezio.ts
src/telemetry/session.ts
src/utils/configuration.ts
src/utils/file.ts
src/utils/linkDatabase.ts
src/utils/localInterrupt.ts
src/utils/reporter.ts

When the user is testing locally, genezio was using `npm link` to install the latest SDK from the local disk. However, we've seen multiple issues with `npm link`:
- the package is removed if the user is running `npm install` or `npm install <package>`
- the user does not understand or forgets to run the `npm link` command
- if `npm` is installed with `nvm` multiple versions of `node` can cause problems
Instead of relying on `link`, we have decided to write directly to `node_modules/@genezio-sdk/...`. We are watching the folder, to see if the package is removed and we put it back if that happens. If `genezio deploy` is executed, we stop all the `genezio local` processes to make sure that the user doesn't push an SDK with localhost URL.

Remove npm link

---

src/packageManagers/npm.ts
src/packageManagers/pnpm.ts

The NPM registry url that was written during `genezio login` was incomplete.

Fix broken links in .npmrc

---

src/generateSdk/templates/packageJson.ts

Change randomly the version of the SDK package when testing locally. This is done to invalidate the webpack caching.

Change randomly the version of the SDK package when testing locally

---

.github/dependabot.yaml

The updates for esbuild to versions greater than 0.18.0 are breaking for genezio.
This PR disables future updates on this dependency.

Ignore esbuild updates greater than 0.18.0

---

src/bundlers/node/nodeJsBundler.ts
src/commands/generateSdk.ts
src/commands/local.ts
src/commands/superGenezio.ts
src/constants.ts
src/telemetry/telemetry.ts
tsconfig.json

This change disallows developers to use `dot access` on properties that are declared as IndexSignature;
Example:
```ts
interface Foo {
a: number;
b: string;
[key: string]: string;
}
function func(foo: Foo) {
foo.a;             // allowed
foo.b;             // allowed
foo.anything;      // not allowed
foo["anything"];   // allowed
}
```
This TS Compiler rule helps other ESLint rules not trigger in the future, when we enable a stricter typed ESLint rule set.

Enable `noPropertyAccessFromIndexSignature` TypeScript compiler option

---

package.json

Temporarily disable ESLint check for pre commit because in this new ESLint TypeScript plugin version, all the warnings have become errors. This makes it very annoying for the programmer because he either has to fix a lot of things not related to his code, or just skip the entire check (including formatting).

Disable ESLint check until more errors get fixed

---

src/utils/file.ts
tests/genezioignore.test.ts

-   [x] 📝 Documentation Update
Fixes genez-io/genezio#616
[Docs PR](https://github.com/Genez-io/genezio-documentation/pull/3)
- `glob` doesn't expect to receive ignore patterns that start with `./`.
- If the pattern ends with `/`, `glob` will ignore the directory entry, but not the files inside; this is most likely what the user expects to happen (and this is also how it is explained in the docs). This is fixed by appending `**` to the pattern if it ends with `/` to match user expectations
- **Improvement**: if the pattern is negated, it gets passed through; `glob` already knows to handle negated patterns.
-   [x] I have updated the …

Improve ignore paths for glob from .genezioignore relative paths

---

.github/workflows/release.yaml

This PR automatically pushes to  the npm registry.
There are 2 ways of triggering this workflow:
- when a version tag is pushed to the repo
- manually
The developer still needs to manually increment the package version in an explicit PR/commit push to `main`.
This will ease the process of releasing the cli tool and make it less error prone.

Add a workflow to automatically push to npm on a new tag

---

package-lock.json
package.json
src/models/yamlProjectConfiguration.ts
src/utils/configs.ts
tests/projectConfiguration.test.ts

We are using [Zod](https://zod.dev), a runtime type check library to enforce the schema read from the configuration file.
This way, we can delegate the task to check the proper types and enforce required fields to Zod.
-   [x] I have updated tests;

Check Yaml Configuration correctness using Zod

---

src/commands/deploy.ts
src/commands/generateSdk.ts
src/commands/local.ts
src/models/projectConfiguration.ts
src/models/yamlProjectConfiguration.ts
src/utils/sdk.ts

The SDK generation system supports AST/SDK gen plugins, so it does not make sense to restrict the `sdk.language` field to the Language type, because if a plugin is present, this field can also take `Language`s that are not supported by us yet.

Treat `sdk.language` field as string to enable custom language plugins

---

src/commands/generateSdk.ts
src/generateSdk/generateSdkApi.ts
src/generateSdk/sdkGenerator/DartSdkGenerator.ts
src/generateSdk/sdkGenerator/JsSdkGenerator.ts
src/generateSdk/sdkGenerator/PythonSdkGenerator.ts
src/generateSdk/sdkGenerator/SwiftSdkGenerator.ts
src/generateSdk/sdkGenerator/TsSdkGenerator.ts
src/generateSdk/sdkGeneratorHandler.ts
src/models/genezioModels.ts

We added the index file (a file that exports all the types and classes of an sdk) in order to have an entry point for our genezio sdk node module, so initially we only added it for the new way of generating the sdk.
Now it is clear that is much cleaner to import everything from one place, so from now on we add this file in the old way of generating the sdk as well. This should not break any existing genezio projects as the old way of importing types and classes still works.

add index file to old ts and js sdk generation

---

src/requests/axios.ts
src/requests/getUser.ts
src/requests/models.ts

Apparenlty, Axios throws when the status code of the request is != 200. I have moved the error check that throws the error message in the Axios intercepter.

Handle Axios error when fetching the user based on access token

---

.eslintrc.cjs
package-lock.json
package.json
scripts/checkConstants.js
scripts/checkUnwantedLogs.js
src/utils/transformDecorators.ts

There was a bug that in the logs from the dashboard, the error stack trace didn't show the original error location. This was due to the fact that the sourcemap, which should have been in the bundled file, was overwritten by the babel transformation. This PR fixes this by setting the sourcemap style to be inline in the babel transformation. Also, due to the fact that the eslint was configured to have scripts in bash, the eslint often stopped Windows users from commiting anything to the Repo. I changed that by making the script in native JS so that they would be OS agnostic.

Bugfix sourcemaps not generating properly due to babel transform

---

src/commands/local.ts
src/generateSdk/utils/compileSdk.ts
src/utils/sdk.ts

delete the destination folder before 1. write sdk to disk, 2. compile sdk or 3. write sdk to node modules
Because the sdk was written to a folder without deleting the contents of the folder first, we had issues with renaming classes because the old classes would remain in the sdk and occupy  space. Solution: delete the destination folder before 1. write sdk to disk, 2. compile sdk or 3. write sdk to node modules

delete the destination folder before any copy or write

---

src/generateSdk/astGenerator/TsAstGenerator.ts

Imports from our own library `genezio_types` in deployed classes were generating SDK errors because the file is ignored by `tsc`. Changing the path by replacing `node_modules` with something else seems to have solved the problem. Need extended testing.

Modify import paths from types in @genezio/types

---

src/commands/deploy.ts
src/commands/local.ts
src/utils/dependencyChecker.ts

We need to check if the user is using an older version of @genezio/types because we migrated the decorators implemented in the @genezio/types package to the stage 3 implementation. Otherwise, the user will get an error at runtime. This check can be removed in the future once no one is using version 0.1.* of @genezio/types.

Check if the @genezio/types version used is older and throw an error.

---

src/commands/deploy.ts
src/commands/local.ts
src/constants.ts
src/utils/dependencyChecker.ts

Use `semver.minVersion` to extract the minimum version from the interval described in `package.json` and use it to compare it with the required interval.

Fix wrong comparison of dep versions.

---

src/constants.ts

`npm install @genezio/types@^1.0.0` would not install the proper version on windows. This is fixed by chaning the command to `npm install @genezio/types@^1.x`
`npm install @genezio/types@^1.0.0` would not install the proper version on windows. This is fixed by chaning the command to `npm install @genezio/types@^1.x`

Fix/npm doesn't install latest genezio types version

---

src/commands/generateSdk.ts
src/generateSdk/utils/compileSdk.ts

When we generate sdk as a node modules package, we have the following flow for sdk generation: temp/sdk is deleted, newSdk is written in temp/sdk, temp/genezio-sdk is deleted, newCompiledSdk is written to temp/genezio-sdk, node_module/genezio-sdk is deleted, newCompiledSdk is written to node_module/genezio-sdk. However, on legacy mode, the sdk was written in the sdkPath provided by user and also compiled in that path which led to the folder being deleted before it could compile its own contents. For this fix i added a default true paremeter at the compileSdk function that, if set to false, will not delete the target directory before compiling. 
-   [x] New and existing unit tests pass locally with my …

we dont delete the folder when we have sdk generation legacy

---

src/bundlers/node/lambdaHandlerGenerator.ts
src/generateSdk/templates/nodeSdkJs.ts
src/generateSdk/templates/nodeSdkTs.ts

Up until now, we did not properly serialize the errors. We were just calling `error.toString()` but that does not include too much information. The proposal in this PR is to serialize Errors containing the following fields: message, code, info. This can be done in a multi language environment and satisfies most of the use cases.

Properly serialize and deserialize errors over the wire

---

src/commands/addClass.ts
src/commands/deploy.ts
src/commands/local.ts
src/commands/superGenezio.ts
src/genezio.ts
src/models/commandOptions.ts
src/utils/configuration.ts

-   [X] 🧑‍💻 Improvement
Add `configFile` option to `genezio local` and `genezio deploy`. The option defaults to `./genezio.yaml` explicitly. Changed the interface of `getProjectConfiguration` to explicitly require the configuration file path to improve readability.

Deploy with custom config

---

src/generateSdk/astGenerator/GoAstGenerator.ts

This solves a bug where a change in the GO parser repository would be inaccessible for users that already compiled a previous version of the repository.
To update the repository, a new release tag should be created on the [GO parser repository](https://github.com/Genez-io/go-ast), and the constant `releaseTag` from the `GoAstGenerator` class should be updated with the new tag.

add version tag to go-ast-parser

---

src/commands/local.ts

The genezio local procces would restart without any changes being made by the user to the watched directories. There were two reasons for this, one of them is that the EOL variable from the OS package was used to split the .genezioignore file lines but this didn't work. To fix this i made a regex that should work on unix and windows systems. The second reason is that VS code would periodically perform git fetch which would change the .git folder. To fix this i just added the .git folder to the .genezioignore path. This means that we should also update any existing templates and examples with the .git folder in the .genezioignore file. We also need to specify in the documentation that the .git folder should be added to the .genezioignore file.
- …

remade the regex to split ignore file properly

---

src/commands/local.ts
src/utils/sdk.ts

Legacy sdk would delete all the contents of a folder, if you were to put the sdk path in root, it would delete all your project files then write the sdk. Now, if we are on legacy sdk we don't delete anything.

we don't delete the sdk if we are on legacy mode

---

src/bundlers/go/goBundler.ts
src/bundlers/go/localGoBundler.ts
src/generateSdk/astGenerator/TsAstGenerator.ts
src/generateSdk/sdkGenerator/GoSdkGenerator.ts
src/generateSdk/sdkGenerator/TsSdkGenerator.ts

GO on genezio now supports map types for parameters and struct properties.
Syntax like `map[string]interface{}` (where the value type is any serializable genezio type) is allowed and can be used in the SDK for GO and TS.

Go map type

---

src/commands/local.ts

Problem: When testing locally on macos, if `client` is not set in `genezioignore`, an infinite loop is triggered due to regex-related issues in `chokidar`.
I couldn't exactly pin-point the regex problems and I couldn't find a decent, os-agnostic solution [1].
To have a robust, os-agnostic solution, this PR disables `fsevents` - a mechanism to trigger filesystem events faster/more efficient than polling - on macos.
This solution should not affect Linux or Windows because these systems have `fsevents` disabled by default.
There might be an alternate solution to remove the regex pattern and create a method that verifies if the string `/node_modules/` is in `<absolute_path>` for every filesystem event triggered. I disregarded this solution because it's error prone and adds a …

GNZ-1441 Disable fsEvent on MacOS to avoid infinite reloading

---

src/generateSdk/astGenerator/GoAstGenerator.ts
src/generateSdk/astGenerator/KotlinAstGenerator.ts
src/utils/dart.ts

Moved the resulting executables for parsing compiled languages in the .genezio folder instead of the users home directory.

move go, kotlin and dart parsers to .genezio folder

---

src/bundlers/node/typeCheckerBundler.ts

Change TypeChecker Bundler to properly run `tsc` in another directory

---

src/bundlers/node/genezioRuntimeHandlerGenerator.ts

-   [X] 🐛 Bug Fix
Fix request headers passed on to the actual user code. Previously, they were left untouched in this handler, but they came altered from the golang client code, which formatted them in HTTP/1.X upper-case compliant manner. This could potentially conflict with how users might format their requests and expect headers.

Force lowercase headers feed into handler

---

src/commands/deploy.ts
src/utils/abTesting.ts
src/yamlProjectConfiguration/v1.ts
tests/performAbTesting.test.ts

-   [x] 🍕 AB Testing
This PR introduces AB testing on the `dev` side for testing the genezio cloud and genezio runtime.
The cloud provider will change seamlessly for newly deployed projects to either `genezio` or `capybaraLinux`.
This change will modify the `cloudProvider` field in the `genezio.yaml`.
This change will only take place if:
- genezio is installed for dev environment
- the initial cloud provider is `genezio` (we don't want to perform ab testing for other experimental tracks such as capybara, cluster or selfHosted)
- `DISABLE_AB_TESTING` is not set
If the developer wants to temporary disable AB testing to make sure the cloud provider is not changed under his feet, he can use `DISABLE_AB_TESTING=true genezio deploy`.
-   [x] My code follows the contributor guidelines of this …

Set up AB testing for cloud providers

---

src/commands/deploy.ts
src/commands/local.ts
src/models/genezioModels.ts
src/utils/configuration.ts
src/yamlProjectConfiguration/migration.ts
src/yamlProjectConfiguration/v2.ts

- class name is now optional in yaml v2
- sdk type has been temporarily removed from yaml v2
- cloud provider has moved to be only per class for now
- backend language is detected by scanning for classes
- the extension of the first found class is considered

[yaml-v2] Improve migration script

---

src/commands/deploy.ts
src/commands/generateSdk.ts
src/commands/local.ts
src/utils/types.ts
src/yamlProjectConfiguration/v2.ts

We have 2 use-cases when interacting with the genezio.yaml config:
- Reading it for consuming the information
In this case we want the configuration to be filled with default
values if the user does not provide values for optional fields.
Example: If region is not specified, it should default to `us-east-1`
- Reading the file just to modify one field and the write it back
In this case we do want to read the original configuration (with no
default filled values) so that we don't modify the user configuration
entierly, only the necessary fields.
Example:
```yaml
name: foo
frontend:
path: .
```
We want to write the `subdomain` field to `frontend`. If we use
the normal `read()`, some values will be defaulted (region for example)
`read()`:
```diff
name: foo
+ region: …
```

Add a mechanism that lets us read either the original config or one filled with default values

---

.eslintrc.cjs

make eslint ignore unused function parameters prefixed with `_`

add eslint unusedvars ignore pattern

---

src/cloudAdapter/aws/selfHostedAwsAdapter.ts
src/models/nodeRuntime.ts
src/yamlProjectConfiguration/v2.ts

-   [x] 📝 Documentation Update
We support `nodejs20x` as default for deploying on AWS Lambda.
The user is still able to set other runtime versions using the configuration yaml file via `nodeRuntime: nodejs18.x` field.
If the `nodeRuntime` is not set by the user, we are using nodejs20 by default.

Set nodejs20.x as default for deploying js/ts projects.

---

src/commands/deploy.ts
src/commands/local.ts
src/yamlProjectConfiguration/v2.ts

This helps us because we don't need to check the type every time we want to access the `frontend` field.

When filling default vaules, convert `frontend` field to always have an array type

---

src/utils/abTesting.ts

The AB Testing PR introduced a verbose error when the project was not found.
This behaviour is expected for projects that were not yet deployed at all. Hence, I want to fail silently.
To do that I created a new axios instance that does not use an interceptor. Unfortunately the code is mostly duplicated in the AB testing method, but this part of the codebase will be deleted after the ab testing is concluded.

Create a new axios instance to do ab testing without throwing errors

---

src/commands/deploy.ts
src/commands/local.ts

This PR makes sure that we are checking `@genezio/types` version only for `js`/`ts` backends.
For other languages, this check makes no sense and it also yields an error on `genezio deploy` or `genezio local`.

Check @genezio/types version only for typescript and javascript backends

---

src/commands/local.ts
src/models/projectConfiguration.ts

This PR includes the following changes (corresponding to the 2 commits)
- Change `nodejs18.x` as default to `node20js.x`.
- Refactor/beautify the code for warning the user that he's testing with a different node version than configured on the server. This check makes sense only for nodejs projects, so I restricted it for those specific languages (ts, js).

Fix node runtime warning

---

src/commands/deploy.ts
src/commands/local.ts
src/yamlProjectConfiguration/v2.ts

If a user just wants to deploy a website, without using a backend, the `language` field is confusing, because it only accepts values that we support for `SDK Generator`. Maybe they do not use a SDK, as they do not have a backend.
Example scenario: I am using Rust Leptos to build a static website, when asked to fill `language`, I am inclined to fill `rust`, but this will give an error, as `rust` is not yet a supported language.

Make language optional for frontend, in case the user doesn't want a generated SDK

---

src/commands/deploy.ts
src/commands/local.ts
src/errors.ts
src/yamlProjectConfiguration/v2.ts

Caught ENOENT error when genezio.yaml file is not found and wrapp it with `UserError`
Changed the `Genezio project URL` log with something more intuitive
Removed annoying package manager prompt on `genezio local` (defaults to npm if not explicit)

catch genezio.yaml ENOENT error + small fixes

---

src/commands/create/create.ts
src/commands/link.ts
src/generateSdk/sdkMonitor.ts
src/genezio.ts
src/models/commandOptions.ts
src/utils/linkDatabase.ts

A bug was introduced where genezio would not generate SDK for linked projects if the YAML did not provide a frontend configuration. This PR fixes it and removes the region from the link map key and the command option
Documentation PR regarding this change: https://github.com/Genez-io/genezio-documentation/pull/54

fix genezio link

---

src/commands/deploy.ts
src/commands/generateSdk.ts
src/utils/configuration.ts
src/yamlProjectConfiguration/migration.ts
src/yamlProjectConfiguration/v2.ts

This removes the need for a `genezio.yaml` configuration file for local SDK generation, a feature needed for custom third-party integrations.
I made a change in the type declaration of the configuration file, so that `language.runtime` and `language.packageManager` are not required. I am not sure that this change won't have any repercussions, so I would like someone who worked here to give their opinion (maybe @costinsin).

remove the need for configuration file on local sdk generation

---

src/utils/decorators/baseDecoratorExtractor.ts
src/utils/decorators/decoratorFactory.ts
src/utils/decorators/goDecorators.ts
src/utils/decorators/jsTsDecorators.ts

Allow decorators in jsdoc and block comments for JS and TS services, instead of just single-line comments.

fix block comment decorators

---

src/bundlers/node/nodeJsBinaryDependenciesBundler.ts

The binary dependency bundler was adding arm64 binary dependencies, even if your runtime and k8s infrastructure are running on x86.

Add support for x86 binary dependencies

---

package-lock.json
package.json
src/commands/generateSdk.ts
src/generateSdk/sdkWriter/jsSdkWriter.ts
src/generateSdk/sdkWriter/sdkWriter.ts
src/generateSdk/utils/compileSdk.ts
src/genezio.ts
src/models/commandOptions.ts

There are situations where you would want to export the JS / TS SDK directly as a tarball. This PR adds this option for the `genezio sdk` command.

Add option to export the SDK as a tarball in JS and TS.

---

src/commands/deploy.ts

This PR correctly propagates the cloud provider if the fairy of ab testing decides to change it.
Before this PR, if the cloudProvider was changed to `capybara`, it wouldn't be updated in the `configuration` object.
Hence, the cloud provider was updated in the `genezio.yaml` to `capybara`, but the project itself was deployed on `genezio`, causing later issues.

Fix cloud provider AB testing

---

package-lock.json
src/index.ts

If you would terminate the proccess in the middle of a deploy, there was a chance that you enter a state where the program can't delete the temporary folder because most likely it is being written in at the same time. This would lead to a state where the proccess would not stop no matter how many times you try to terminate it. To fix this, i added a try catch on delete folder that logs the error, behaivour which is normal for mid execution interupts for any other platform.

added try catch on delete folder

---

src/errors.ts
src/utils/configuration.ts

Added a warning when a class is defined in both the genezio.yaml file and in the decorators resulting in definition overwrites 

Fix overlapping classes in yaml and decorator bug

---

src/requests/axios.ts

This addresses the popular `error reading property code of undefined`, which occurs whenever the server crashes for various reasons and the HTTP response doesn't have a structure that can be understood by the CLI. 
This change catches such errors and encourages the users to open a GitHub issue regarding their problem.

catch internal server errors and display appropiate message

---

src/bundlers/node/clusterHandler.ts
src/bundlers/node/clusterHandlerGenerator.ts

Passing binary data (pictures, archives, etc.) to a Cluster Genezio HTTP method would result in byte scrambling of the file and ultimately in incorrect file transfer.

fix incorrect building of body containing binary data

---

src/bundlers/node/typescriptRequiredDepsBundler.ts

The CLI checks for the package @types/node to be installed on every typescript project, but on monorepo projects, it searches in the root folder, leading to installing the package every time.
This solves the annoying issue of the server reloading at the start of `genezio local`.

fix @types/node install bug

---

package-lock.json
src/bundlers/node/lambdaHandlerGenerator.ts
src/generateSdk/sdkGenerator/JsSdkGenerator.ts
src/generateSdk/sdkGenerator/TsSdkGenerator.ts

I added a check on the Lambda handler generator that populates a GenezioContext object with the requestContext and the headrs of the incoming request from AWS. I also added a check in the Ts/Js SdkGenerator to add a new property to a GnzContext object named `isGnzContext`. this property is added only if the first parameter of a function is a GnzContext. It helps the lambdaHandler to know whether to populate that parameter or not. 

Create rate limiter middleware

---

src/bundlers/go/localGoMain.ts
src/generateSdk/astGenerator/DartAstGenerator.ts
src/generateSdk/astGenerator/GoAstGenerator.ts
src/utils/process.ts

On windows the AST generation for GO was not working for paths that had a space in them. To fix this i used `$` provided by execa which is platform agnostic and handles spaces in paths automatically. Moreover, on Windows we had a permisions problem on local in that everytime the go code was compiled into a .exe file, it needed user permision to acces the internet, fixed this by specifying that the executable only runs on localhost.

Fixed space in path for go bug

---

src/commands/local.ts
src/requests/axios.ts

We were receiving sentry errors regarding connection to the local server for users' applications. This is an expected error that used to have a fallback mechanism that would attempt to restart the process. That mechanism was lost because we stopped returning AxiosErrors from the Axios interceptor.
This PR returns the unmodified AxiosError from the interceptor in case of a missing response (indicating a problem reaching the server), which will allow the fallback to take place, as well as sending a custom UserError which should no longer be captured by Sentry.

Fix connection error fallback mechanism

---

src/bundlers/go/goBundler.ts
src/bundlers/node/nodeJsBinaryDependenciesBundler.ts
src/bundlers/node/nodeJsBundler.ts
src/bundlers/node/nodeJsLocalBundler.ts
src/cloudAdapter/genezio/genezioAdapter.ts
src/commands/bundle.ts
src/commands/deploy.ts
src/commands/local.ts
src/models/cloudProviderIdentifier.ts
src/models/projectConfiguration.ts
src/requests/getAuthStatus.ts
src/utils/abTesting.ts
src/utils/servicesEnvVariables.ts
src/yamlProjectConfiguration/migration.ts
src/yamlProjectConfiguration/v2.ts
tests/performAbTesting.test.ts
tests/requests/deployCode.test.ts

-   [X] 🔥 Breaking change
Update cloud provider names and maintain backwards compatibility with the old ones.
Changed the default provider to CAPYBARA_LINUX.
New cloud provider names:
genezioCloud
genezioCloudUnikernel
genezioAws
genezioCluster
This change does not affect self hosted AWS.

Migrate to new cloud provider naming

---

src/commands/deploy.ts

Remove a/b testing from deployments. I've decided to leave the a/b testing logic there in case we will need it on a future cloud provider (genezio-unikernel is the first one to come to mind).

Remove a/b testing for runtime

---

src/models/projectConfiguration.ts
src/yamlProjectConfiguration/v2.ts

Revert back the default provider change from `genezio-cloud` to `genezio-aws`.

Revert default provider change back to aws

---

src/bundlers/node/genezioRuntimeHandlerGenerator.ts

The url returned by the runtime now has the functionId as part of the subdomain. Previously, it was the first element of the path. As a result, in order to take the method name, we need to take the first part of the path.

Fix Runtime handler URL composition

---

src/commands/create/create.ts
src/commands/link.ts
src/generateSdk/sdkMonitor.ts
src/genezio.ts
src/utils/linkDatabase.ts
tests/commands/create/create.test.ts

-   [x] 🔥 Breaking change
We would like to know the SDK language of a linked frontend when writing it. Until now, we would always write the JS/TS SDK, but now a frontend in any supported language can be linked.

Change genezio link internal structure to contain SDK language

---

src/bundlers/node/containerManifest.ts
src/models/projectOptions.ts

Remove old node runtime versions (node16 and node18). Until future stable node versions, the only supported runtime will be node20.

remove old node runtimes

---

src/commands/local.ts

Genezio local should still use the aws handler, as the request still use the aws interface.

use aws handler for genezio local

---

src/bundlers/bundler.interface.ts
src/bundlers/go/goBundlerBase.ts
src/bundlers/node/nodeJsBundler.ts
src/cloudAdapter/cloudAdapter.ts
src/cloudAdapter/cluster/clusterAdapter.ts
src/cloudAdapter/genezio/genezioAdapter.ts
src/commands/deploy.ts
src/requests/deployCode.ts

For the new functions feature, we no longer bundle the users code, meaning there could be conflicts between our handler (previously hardcoded to `index.mjs`) and user defined files. This PR checks for conflicts and changes the handler filename when necessary, sending the handler name for every deployable unit (class or function) to the core service, in order to load the right file when booting the VM.

send entry file in deploy endpoint

---

src/bundlers/go/genezioRuntimeGoBundler.ts
src/bundlers/go/localGoBundler.ts
src/commands/deploy.ts

Genezio Cloud currently has a few bugs when deploying GO, especially from platforms other than Linux. While we search for a solution regarding this, this PR aims to redirect all GO deployments to the AWS Lambda cloud provider.

temporarily redirect go functions to aws lambda

---

src/commands/deploy.ts

Before this change, auto login would only be called for projects that have backend deployment. If the project was only deploying frontend, the auto login code would not be called.

Move deploy auto login before backend/frontend deployment

---

src/bundlers/node/genezioRuntimeHandlerGenerator.ts
src/bundlers/node/lambdaHandlerGenerator.ts

If the first parameter is `null`, calling `isGnzContext` on that value will result in a crash.

Fix for issue when isGnzContext is called on 'null' value.

---

src/commands/create/create.ts
src/commands/deploy/nextjs.ts
src/requests/getProjectInfoByName.ts
src/utils/servicesEnvVariables.ts

We don't want to automatically use the package.json name if the project exists, because it could overwrite the existing project by accident.

Prompt user to select project name if the package.json name project exists

---

src/genezio.ts

A previous PR fixed `--path` not working in the `genezio create nextjs/expressjs/serverless` command by adding option passtrough. This broke the `--logLevel` global option. This PR fixes the problem, while still making the `genezio create --path`  option work.

[bugfix] Allow logLevel option to be used anywhere in command

---

src/commands/deploy/nextjs.ts

The if condition was not okay before. For a `distributionUrl` that is starting with `https://`, the condition `!distributionUrl.startsWith("http://")` is true - making the whole if condition true.
Hence, we ended up displaying `https://https://domain`.

Fix condition to correctly form the distribution URL

---

src/commands/local.ts

Fixed a bug that broke genezio local if trying to return a body of type object from a function. Also, fixed query params which broke since we trimmed the URL for local functions.

allow object body and query params in genezio local functions

---

src/bundlers/node/nodeJsLocalBundler.ts

The local wrapper logged the port where the application was running. That log could be misleading for the user, as that port is not exposed directly to the user, but to our express "proxy" serving all the functions from the same port.

remove console log with port on local function wrapper code

---

src/bundlers/node/nodeJsBundler.ts

We only use sourcemaps for error stack traces, which does not require having the original file content. This change will slightly lower the bundled code size in case there is a lot of code, because it won't store the original code in the source map anymore.

Make Source Maps smaller by avoiding to include original file content

---

src/bundlers/node/nodeJsBundler.ts

If the user already has a `index.mjs` file for a function and he also uses genezio classes, we might override the handler for the classes when we copy incorrectly the `index.mjs` file. We must handle `*.mjs` and *.cjs` files as js files.

Bug fix: we could override incorrectly a index.mjs handler

---

src/utils/configuration.ts

Currently, the overlapping classes error appears when the user declares a file that contains a class that is marked for deployment in Genezio.
This is happening because `deployDecoratorFound` is false, hence it will execute the `else` branch adding an `""` string.
The warning should appear if `r` is defined and contains classes and if `deployDecoratorFound` is true.

Fix overlapping warning

---

src/commands/login.ts

If `CI` is set to true it means the genezio process runs in a continuous integration environment.
Trying to open the browser will make the process hang indefinitely.
This eats away GitHub actions minutes for failed logins because it will hang until the action timeouts or is cancelled.

Prevent browser redirect at login if CI is set to true

---

package-lock.json
src/commands/create/create.ts
src/genezio.ts
src/models/commandOptions.ts

You can now create a default nextjs app by adding --default, this way you do not need to utilize the nextjs wizard.

Enabled default creation on nextjs w/o wizzard

---

src/commands/deploy/genezio.ts

Throw error if frontend `publish` folder is missing instead of just returning a warning.

Throw error if frontend publish folder is missing

---

src/commands/deploy/nextjs/deploy.ts

If `next.config.js` is missing, open-next will throw an error. We add an empty config file to make it work automatically. 

Add an empty next.config.js file if missing.

---

src/commands/deploy/utils.ts
src/utils/environmentVariables.ts

This PR auto-detects missing environment variables and prompts the user to confirm if genezio should also set them.
E.G.:
```
? We detected that TEST, OPEN_API_KEY are not set remotely. Do you want us to set them for you? [yes/no] no
Skipping environment variables upload.
```
This interactive behaviour is not triggered when `CI = true`.

Autodetect and prompt the user to set env vars

---

src/commands/deploy/genezio.ts
src/commands/deploy/nextjs/deploy.ts
src/commands/deploy/utils.ts
src/projectConfiguration/yaml/v2.ts
src/utils/environmentVariables.ts
tests/utils/environmentVariables.test.ts

This PR adds support for `backend.environment` in the `genezio.yaml`:
```yaml
backend:
environment:
OPENAI_API_KEY: ${{env.OPENAI_API_KEY}}
URL: ${{backend.functions.hello.url}}
TEST: "test"
```
This feature will coexist with `genezio deploy --env <envFile>`.
The order of importance for setting env vars is as following:
- If the user executes `genezio deploy --env <envFile` all the contents of the .env file will be set remotely - no questions asked.
- If `backend.environment` is set in the `genezio.yaml`, genezio will do the following:
- for `TEST: "test"`- it will set the clear text value.
- for `URL: ${{ backend.functions.<function_name>.url }}` - it will expand the …

Add backend.environment to the configuration file

---

src/commands/bundle.ts
src/genezio.ts
src/models/commandOptions.ts

We want to be able to bundle a function without the need of a genezio.yaml file
This PR allows you to do that if all your command options are properly set

Make bundle function work without genezio yaml

---

src/commands/deploy/genezio.ts
src/commands/deploy/utils.ts
src/models/requests.ts
src/projectConfiguration/yaml/models.ts
src/projectConfiguration/yaml/v2.ts
src/requests/authentication.ts
src/utils/scripts.ts

The genezio.yaml fields can be configured as following:
```
settings:
passwordReset:
redirectURL: https://${{frontend.wild-red-boars.name}}.app.genez.io/auth/resetPassword
emailVerification:
redirectURL: [${{backend.functions.hello.url}}](ttps://${{frontend.wild-red-boars.name}})/auth/verifyEmail
```

Add settings.<template-type>.redirectUrl

---

src/commands/deploy/nuxt/deploy.ts

We should use `/` as separator in entryFile field, not a platform specific separator.

Use / instead of platform dependent path separator.

---

sdk-external-modules/remote-ts/src/remote.ts
src/bundlers/node/genezioRuntimeHandlerGenerator.ts
src/bundlers/node/lambdaHandlerGenerator.ts
src/generateSdk/astGenerator/TsAstGenerator.ts
src/generateSdk/sdkGenerator/TsSdkGenerator.ts
src/models/genezioModels.ts

Added support for the javascript primitive [`bigint`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt), which enables the use of 64-bit integers. The problem with this primitive is that it is not serializable by default. We needed to do a little hack to send this over the wire when used as a parameter or return type of a genezio typsafe function.

add bigint suuport for typesafe genezio TS

---

src/commands/deploy/docker/deploy.ts

Add a space after `/bin/sh -c`.

add empty space before cmd

---

src/commands/deploy/genezio.ts

Allow users to specify subdomains that include uppercase characters in their genezio.yaml.
The server side logic will now perform another validation and cast the string to lowercase before creating the frontend. The CLI will still however return errors if forbidden characters are used or maximum length is surpassed.

allow upper case for subdomain

---

src/commands/analyze/command.ts
src/commands/analyze/utils.ts

Save the `scripts` field as an array always - there are 2 reasons:
- It makes the code easier on the dashboard side because it will treat this field as an array of strings
- It's an indication for the user that he can add a list of commands in the`scripts`.

[Analyze] Set scripts as an array always

---

src/commands/deploy/command.ts
src/commands/deploy/genezio.ts
src/commands/deploy/nextjs/deploy.ts
src/commands/deploy/nextjs/edge.ts
src/commands/deploy/nuxt/deploy.ts
src/commands/deploy/utils.ts

Support custom path for SSR frameworks.
As a fallback/backwards compatibility reasons (old genezio.yaml files) - everywhere where `cwd` is not set, we will use `process.cwd()` which is the root directory of the project.
The path is set in the `genezio.yaml` in each ssr component sections:
```yaml
nextjs
path:
nitro:
path:
nuxt:
path:
```

Support custom path for SSR frameworks

---

src/commands/deploy/genezio.ts
src/models/projectOptions.ts

Force pip to install x86 packages, because runtime architecture is x86.

Force pip to install x86 packages

---

src/commands/analyze/command.ts

This PR changes the order of the frontend frameworks so Vue, Svelte have priority over Vite.
TL;DR; We want to expose to the user the actual frontend framework used (Vue, Svelte), not the local dev tool a.k.a Vite.
Generally, Vite is used to create templates and build frontends - it's not a frontend framework per se.
Modern frameworks such as Vue or Svelte are using vite by default under the hood, so it's redundant to give this information to the user. It's better to confirm with him the actual framework used.
A bit more complex is React that can be build with CRA or Vite - in this case it make sense to tell the user which build/local dev tool is used under the hood.
- …

Reorder frameworks to detect vue/svelte instead of vite

---

src/generateSdk/astGenerator/TsAstGenerator.ts

I've fixed two problems in this PR:
- We were doing the `this.getAllFiles(typescriptFiles, ".");` and `const program = typescript.createProgram(typescriptFiles, {});` operations multiple times, each time for every genezio class.
- `getAllFiles` was retrieving also the contents of the `.git` folder.

Optimise ts sdk generator process

---

src/commands/deploy/utils.ts
src/utils/file.ts

Rules starting with `!` in `.gitignore` files trigger a bug that would result in an empty archive being uploaded for user's code. Simply ignoring these rules solves this issue.

ignore reinclusion rules in .gitignore

---

src/commands/analyze/command.ts
src/commands/analyze/constants.ts

This repository - https://github.com/dternyak/React-Redux-Flask - uncovered the following bugs:
1. Did not not check if the file existing before attempting to read it - now we log the error and continue with default values
2. The Flask pattern was to restrictive and matched only `app = Flask(__name__)` - now it can match more complex inits such as `app = Flask(__name__, static_folder="./static/dist", template_folder="./static")`
I extended the same logic for FastAPI and Django - we should match pattern with arguments in the constructor - e.g.:
```
application = get_wsgi_application(debug=True)
application = get_wsgi_application(config="my_config", mode="dev")
app = …
```

Analyze python fixes

---

src/commands/analyze/command.ts

-   [] 🧑‍💻 Improvement
Reverting containers detection because it's not used now (we cannot build docker images in the build machine).
Detecting containers is confusing and buggy until we implement a decision tree/graph of choice for detecting components.
This algorithm will come in a subsequent PR in the future.

Temporarily revert detecting containers

---

src/commands/deploy/command.ts

Some ssr framework have a simple `genezio.yaml` (slightly outdated):
```yaml
name: genezio-nextjs-getting-started
yamlVersion: 2
```
We should also support deploying those - so if nextjs | nuxt | nitro is not present in the `genezio.yaml`, we continue with detecting for a deployable component. 

Fix backwards compatibility for ssr

---

src/commands/analyze/command.ts

To retrieve the contents we should use the fullpath relative to where the genezio.yaml is

Fix entryfile path regression

---

package-lock.json
package.json
src/cloudAdapter/genezio/genezioAdapter.ts
src/commands/analyze/command.ts
src/commands/analyze/frameworks.ts
src/commands/deploy/command.ts
src/commands/local.ts

-   [x] 🍕 Release v.3.0.8
This PR releases only some hot fixes that have been cherry-picked from `dev`.
Each commit corresponds to a hot-fix, check the description for more information.
Note: This commit is a temporary fix and it's not on the `dev` branch (for the next release, this if should be removed):
https://github.com/Genez-io/genezio/pull/1610/commits/ab99ab26962ff4d57e21d7ec5f54775c32d72632
The commit treats the following use case: Users might end up having `backend` and `nextjs` in their `genezio.yaml` - we currently don't support deploying both.
A temporary workaround is to ignore deploying the nextjs component. 
Until this is fixed, users should use 2 different genezio.yaml file to deploy both components.
-   [ …

Release v3.0.8

---

src/commands/deploy/docker/deploy.ts

Check if exposePort is null

---

package-lock.json
src/commands/deploy/genezio.ts

If the user have a pip.config like this:
```
[global]
user = yes
```
need to install with --no-user

Add --no-user to pip install

---

src/commands/local.ts

Remove set Cors from node.js local wrapper
Context: In the local environment, we configure CORS with a wildcard (`*`) to simplify development. However, when the application is deployed, the user is responsible for setting the appropriate CORS configuration themselves. This current setup may lead to issues, such as a conflict when the wildcard (`*`) is set twice, resulting in errors.

Remove set Cors from node.js local wrapper

---

src/commands/deploy/nextjs/deploy.ts

This PR fixes an issue where Next.js deployments were failing for TypeScript projects due to direct imports of `.ts` files in the generated configuration. TypeScript doesn't allow importing `.ts` files directly without enabling the `allowImportingTsExtensions` compiler flag.
```
Failed to compile.
./next.config.ts:2:24
File "/home/runner/work/genezio-tests/genezio-tests/test_genezio_create.py", line 1[50](https://github.com/Genez-io/genezio-tests/actions/runs/12700753372/job/35426649464#step:17:51), in <module>
test_genezio_create()
File "/home/runner/work/genezio-tests/genezio-tests/test_genezio_create.py", line 144, in test_genezio_create …
```

Remove .ts extension from Next.js config imports

---

src/commands/analyze/command.ts
src/commands/analyze/frameworks.ts
src/commands/deploy/command.ts
src/commands/deploy/remix/deploy.ts
src/commands/deploy/utils.ts
src/models/projectOptions.ts
src/projectConfiguration/yaml/v2.ts

This PR implements Remix deployment support, handling both Remix Vite and Classic Remix architectures.
The implementation dynamically identifies and manages two distinct build patterns:
1. **Remix Vite Build**
- Uses the modern Vite bundler
- Output structure:
```
build/
├── client/        # Client-side assets
└── server/        # Server-side bundle
└── index.js   # Server entry point
```
2. **Classic Remix Build**
- Traditional Remix bundler
- Output structure:
```
build/
├── index.js      # Server entry point
└── public/       # Static assets
```
In both cases index.js will always be a module bundle.
Both variants are served through an Express.js server with specific …

Add support Remix.js

---

src/commands/local.ts

Updated logic to let users configure the port via an environment variable for frameworks like Nest.js. If the port is not explicitly set, it falls back to a default. For Nest.js, a user-friendly error is thrown if the port is missing.

Allow Users to Set the Port for SSR Frameworks

---

src/commands/analyze/command.ts

This PR:
- Reorders the detection rules to make sure we are detecting any possible backend (python, node, express, flask etc.) then SSR frameworks, then frontend frameworks.
- Reordering I'm making sure that I detected backends and I can stop detecting any SSR because a cross-deployment (fullstack) with these 2 types of component won't work
Note: It's best to review each commit because I ordered the changes to make sense.
This is a temporary fix (for this release) to not break projects like the one below which have backend with express and frontend with next:
https://github.com/andreia-oca/FullstackEcommerce
-   [x] My code follows the contributor guidelines of this …

Temporarily disable next detection

---

src/functionHandlerProvider/providers/AwsFunctionHandlerProvider.ts

This PR fixes an issue where the Python AWS handler would fail when:
- The handler function returns None
- The handler function returns a non-dictionary value
- The response object lacks a headers dictionary
Changes:
- Added proper handling for None responses
- Added conversion of non-dict responses to a valid response format
- Ensured headers dictionary is always present in the response
- Added string conversion for non-dict responses
This prevents errors like "TypeError: argument of type 'NoneType' is not iterable" and "Invalid response type" from occurring when handlers don't return the expected response format.
-   [x] My code follows the contributor guidelines of …

fix: Handle None and non-dict responses in Python AWS handler

---

src/commands/deploy/docker/deploy.ts
src/commands/deploy/nestjs/deploy.ts
src/commands/deploy/nextjs/deploy.ts
src/commands/deploy/nuxt/deploy.ts
src/commands/deploy/remix/deploy.ts
src/commands/deploy/zip/deploy.ts

This update improves the user experience by displaying the application dashboard URL after deploying an app. Previously, users deploying a cloned repository would not know where to access the dashboard, logs, and other related features. 

Show app dashboard url

---

src/commands/deploy/nextjs/deploy.ts

This PR resolves an edge case where Next.js deployments could fail due to incorrect module syntax in generated configuration files. Specifically, the issue arose when our generated next.config.js always included an import statement, even in projects configured to use CommonJS.

fix: handle ESM/CommonJS module syntax correctly in Next.js config

---

src/commands/deploy/nextjs/deploy.ts

Resolved an issue where running `npm ci` without an existing `package-lock.json` file caused the command to fail with an EUSAGE error. The fix ensures that the script checks for the presence of `package-lock.json` before attempting a clean install.

fix: check if package-lock exists for clean install

---

src/commands/deploy/nextjs/deploy.ts

When no Next.js config file exists and a new one is created, the code need to attempt to reassign the file extension to `existingConfig`
```
The build failed due to an error related to a missing file or directory when renaming a file in the '/tmp/genezio-147/wex0mj/src' directory. The build process was unable to locate the file 'next.config.undefined' while trying to rename it to 'base-next.undefined'.
```

fix: process was unable to locate the file 'next.config.undefined' 

---

src/commands/deploy/genezio.ts
src/commands/deploy/utils.ts
src/commands/local.ts
src/utils/environmentVariables.ts

Constructs like `${{ env.VITE_TEST }}`are not permitted in the `frontend.environment` because they don't make sense.
This kind of construct is used on the backend to hide sensitive values (that are read from a local-only`.env` file) and still create a full IaC configuration file that can be versioned in `git`.
The same idea does not make sense for the frontend because there are no secret environment variables there.
To avoid any confusions, we don't allow `TEST: {{env.VITE_TEST}}` on the frontend - the user should either use the actual value `TEST: "my-test-var"` or to use `.env` file that will be managed by `vite`-like tools.
Note: `genezio deploy --env <envFilePath>` …

Propagate the env file correctly

---

src/commands/analyze/command.ts
src/commands/deploy/genezio.ts
src/models/projectOptions.ts
src/utils/detectPythonCommand.ts

Add the possibility to choose the python version

feat: Add the possibility to choose the python version

---

src/models/projectOptions.ts

Updates the default Python version from 3.11 to 3.13.
- Changed `DEFAULT_PYTHON_RUNTIME` to "python3.13.x"
- Updated `DEFAULT_PYTHON_VERSION_INSTALL` to "3.13"

chore: update default Python runtime to 3.13

---

src/commands/analyze/command.ts
src/commands/deploy/command.ts
src/commands/deploy/genezio.ts
src/commands/deploy/nestjs/deploy.ts
src/commands/deploy/nextjs/deploy.ts
src/commands/deploy/nuxt/deploy.ts
src/commands/deploy/remix/deploy.ts
src/commands/deploy/streamlit/deploy.ts
src/models/projectConfiguration.ts
src/models/projectOptions.ts
src/projectConfiguration/yaml/models.ts
src/projectConfiguration/yaml/v2.ts

To allow the backend to handle backwards compatibility issues related to latest `language.runtime` we should prevent pushing `nodeRuntime` and `pythonRuntime` to the backend. These should be set only when the user specifically sets them in the `genezio.yaml`.

Prevent sending a runtime default to the backend

---

src/commands/local.ts
src/functionHandlerProvider/providers/AwsFunctionHandlerProvider.ts

This PR fixes an issue with Python module imports where paths containing hyphens would cause import errors. The fix converts hyphens to underscores in module names to ensure Python import compatibility.
- Added conversion of hyphens to underscores in Python module path processing
- Ensures module names follow Python naming conventions
Before:
`genezio-python-executor/index.py` -> `genezio-python-executor.index` (invalid)

fix: convert hyphens to underscores in Python module imports

---

src/cloudAdapter/cloudAdapter.ts
src/cloudAdapter/genezio/genezioAdapter.ts
src/commands/deploy/command.ts
src/commands/deploy/docker/deploy.ts
src/commands/deploy/genezio.ts
src/commands/deploy/nestjs/deploy.ts
src/commands/deploy/nextjs/deploy.ts
src/commands/deploy/nuxt/deploy.ts
src/commands/deploy/remix/deploy.ts
src/commands/deploy/streamlit/deploy.ts
src/commands/deploy/utils.ts
src/models/environmentVariables.ts
src/requests/deployCode.ts
src/utils/environmentVariables.ts

Support setting environment variables concurrently with the deployment in the same request.
This PR does the following:
- retrieves the environment variables before the deployment to send them in the same request (rather than after the deployment was succesful as it is now)
- reimplements some UX features we have to make sense with the new approach: 
The features:
- set environment variables with `genezio deploy --env .env` - now this atomically sets environment variable in a single request to the backend and cloud provider.
- Proactively ask the user to set `--env` if an `.env` file is detected - this question is now asked before the deployment.
- Warn the user if …

Add support for adding env vars at deploy time

---

src/commands/local.ts

Modifies port setting logic to preserve existing environment variable values.
- Adds check before setting port environment variable
- Prevents overwriting manually configured ports
- Improves predictability for custom configurations

fix: preserve existing port environment variables

---

src/commands/analyze/command.ts
src/commands/analyze/constants.ts
src/commands/analyze/frameworks.ts
src/commands/analyze/utils.ts
src/models/projectOptions.ts

Improves how we handle TypeScript compilation output paths by properly respecting `tsconfig.json` settings. This ensures we correctly reference the compiled files during deployment, taking into account the project's TypeScript configuration.
```
// tsconfig.json
{
"compilerOptions": {
"outDir": "./build",
"rootDir": "./src",
"module": "esnext"
}
}
```
For an entry file at `src/api/index.ts`, the system will now correctly resolve to `build/api/index.mjs`.
If no tsconfig.json is found or settings are missing:
- `outDir`: defaults to "dist"
- `rootDir`: defaults to "."
- `module`: defaults to "commonjs"
- …

feat: add support typescript backends on genezio analyze

---

src/cloudAdapter/genezio/genezioAdapter.ts

Allow bigger bundle size (5GB) for persistent functions

allow 5GB bundle size for persistent functions

---

src/commands/env.ts

Adding quotes to escape special characters in the env var value when revealing them.

[getenv] Escape env vars content when revealing them

---

src/utils/configuration.ts

It seems that use `persistent` as boolean in the decorator `GenezioDeploy` doesn't work. I am not exactly sure why.
The current fix is to use `persistent` as a string and later cast it to a boolean in the codebase.
Usage example:
```
@GenezioDeploy({
type: "jsonrpc",
persistent: "true"
})
```

Fix persistent configuration for classes decorators

---

package-lock.json
src/commands/deploy/docker/deploy.ts

This PR fixes an issue with command execution in Docker containers where commands with multiple arguments were not being properly quoted when using `/bin/sh -c`.
- Modified the command construction to always quote the entire command when using `/bin/sh -c`
- This ensures proper execution of commands with multiple arguments (e.g. `python app.py`, `node server.js`, etc.)

fix: properly quote commands in docker container execution

---

src/commands/deploy/utils.ts
src/commands/local.ts
src/models/requests.ts
src/projectConfiguration/yaml/v2.ts
src/requests/database.ts

Support for dedicated atlas clusters. To activate this, a user should have a custom subscription.
How can one use this:
```yaml
databases:
- name: internal-gta-db
type: mongo-atlas
clusterType: dedicated
clusterName: my-atlas-cluster
clusterTier: M30
```
[backwards compatibility] For configs that do not explicitly set the `clusterType` to `dedicated`, we will use the shared cluster:
```yaml
databases:
- name: internal-gta-db
type: mongo-atlas
```
or
```yaml
databases:
- name: internal-gta-db
type: mongo-atlas
clusterType: shared
```
-   [ ] …

Support mongo dedicated clusters

---

src/cloudAdapter/cloudAdapter.ts
src/commands/deploy/docker/deploy.ts
src/commands/deploy/genezio.ts
src/models/projectConfiguration.ts
src/projectConfiguration/yaml/v2.ts

The `healthcheckPath` field is used during the deployment of persistent functions to validate that the new deployment is healthy before returning a status.

feature: add healthcheckPath field to yaml for persistent functions
